### ISSUE TITLE
[Téléphone] Options Contacts

### ISSUE THREAD

**Issue by Maskowh** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

Téléphone

### Explain the current situation that you do not think is right.

Options disponibles:
![image](https://user-images.githubusercontent.com/123783610/216814862-15190759-7a74-4560-be44-38ca025d341d.png)

### How is the improvement you propose?

Ajouter les options "Envoyer ma position" et "Envoyer ma destination"

**Comment by NariieL** [comment]
Nous sommes contre ! <3
