### ISSUE TITLE
[Telephone] Indicateur dans l'annuaire entreprise si une entreprise est en service ou non

### ISSUE THREAD

**Issue by Maskowh** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Indicateur dans l'annuaire entreprise si une entreprise est en service ou non

### Explain all the steps and mechanics clearly and precisely.

Texte des entreprises en service en vert, hors-service en rouge, FDOs en blanc (considérés toujours en service)

### Why would this feature be useful?

Permet de décharger les répondeurs entreprises de message apportant peu de RP: "Est-ce que vous êtes ouverts?" -> "Oui" ou Pas de réponse.
Permet de relever facilement si une entreprise est régulièrement hors-service et donc de se plaindre que le service n'est pas assuré.
Permet à un employé d'une entreprise de savoir si au moins un collègue est en service, sans se reposer sur un intra extérieur au jeu.

**Comment by NariieL** [comment]
Nous sommes contre ! <3
