### ISSUE TITLE
[Telephone] Détails de l'appel dans le Répondeur Entreprise

### ISSUE THREAD

**Issue by Maskowh** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

Telephone

### Explain the current situation that you do not think is right.

Les options disponibles actuellement
![image](https://user-images.githubusercontent.com/123783610/216810783-c1ee59c5-e323-4dac-93be-56b64d74c77d.png)

### How is the improvement you propose?

Ajouter une option Détails indiquant l'heure de l'appel, l'heure de prise d'appel et par quel employé, l'heure de clôture d'appel et par quel employé.

**Comment by NariieL** [comment]
Nous sommes... Aucune idée ! Tu peux montrer à quoi ça ressemblerait ?

**Comment by Maskowh** [comment]
Hello, j'abandonne cette issue pour me concentrer sur d'autres.

Cette issue peut être fermée
