### ISSUE TITLE
[Telephone] Eviter le missclic de suppression de note

### ISSUE THREAD

**Issue by Maskowh** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

Telephone

### Explain the current situation that you do not think is right.

![image](https://user-images.githubusercontent.com/123783610/216814261-7f326019-9d81-415f-8b04-d3d7ff50f56c.png)
![image](https://user-images.githubusercontent.com/123783610/216814276-51b808c1-de83-4692-9b9c-09adce5ffe10.png)
Actuellement: La hitbox de suppression est très large, allant jusqu'à l'icône de sauvegarde, dont la hitbox est elle plutôt fine.

### How is the improvement you propose?

A minima revoir les hitboxs, et peut-être en profiter pour rajouter une demande de confirmation à la suppression de note?

**Comment by NariieL** [comment]
Nous sommes pour ! <3

**Comment by Maskowh** [comment]
https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/assets/123783610/41246b00-7c62-43f7-b595-2c25bf9eafd3
