### ISSUE TITLE
[Telephone] Onglet dans l'appli Banque d'historique des virements

### ISSUE THREAD

**Issue by Maskowh** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Onglet dans l'appli Banque d'historique des virements

### Explain all the steps and mechanics clearly and precisely.

Ajouter un onglet dans l'appli Banque d'historique des virements: Date, emetteur, recepteur, montant.

A la manière de l'appli "Téléphone", ayant plusieurs onglets en bas de l'appli, avoir deux onglets:
- Le premier "Compte", reprenant l'affichage actuel
- Un deuxième "Virements" représentant une liste des derniers virements effectués (au cours des 30 derniers jours par exemple). Cela comprend les virements effectués et reçus. L'affichage serait très classique, comme ce qu'il se fait dans l'appli Twitch News ou le répondeur entreprise.

### Why would this feature be useful?

Trace les virements effectués. 
Permet d'avoir des preuves d'échanges d'argent, pour des enquêtes par exemple.

**Comment by NariieL** [comment]
En combinaison de https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/issues/124 ?

**Comment by Kedrihan** [comment]
Oooh à voir !
On peut faire un onglet Factures sur l'app Banque en effet !

**Comment by NariieL** [comment]
Cela fait un moment que ça a été nôté sur la note de patch, encore merci. <3
