### ISSUE TITLE
[Notification] Notification de virements

### ISSUE THREAD

**Issue by Maskowh** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

Notifications

### Explain the current situation that you do not think is right.

Actuellement, que l'on reçoive un salaire ou un virement, l'affichage est le suivant: 
![image](https://user-images.githubusercontent.com/123783610/216816523-462964cc-4b12-43f0-83d0-5c0e73bcda8e.png)

### How is the improvement you propose?

Dans le cas d'un salaire: "Votre salaire [en service|hors service] de [montant] vient d'être versé sur votre compte.
Dans le cas d'un virement: Un virement de [montant] de [expediteur] vient d'être versé sur votre compte.

**Comment by NariieL** [comment]
Nous sommes pour !
