### ISSUE TITLE
[Module UPW] Ajout des véhicules électriques

### ISSUE THREAD

**Issue by Zocaxu** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Ajout des véhicules électriques :

- HUD adapté
- Features véhicule adaptées
- Nouvelle feature/farm pour UPW via les bornes de recharge
- Commande de véhicules électriques pour UPW
- Entretien des véhicules électriques par UPW
- Concessionnaire électrique

### Explain all the steps and mechanics clearly and precisely.

# Module : Véhicules électriques UPW
Modèles : 'Dilettante', 'Khamelion', 'Surge', 'Voltic', 'Cyclone', 'Neon', 'Raiden','Tezeract', 'Imorgon', 'I-Wagen', 'Omnis e-GT', 'Caddy', 'Airtug', 'Rocket Voltic'

## HUD
Changement de l'HUD pour les véhicules électriques

### Tableau de bord
- [x] Icône d'essence -> Icône de batterie
- [x] Réservoir d'huile -> batterie
- [x] Jauge d'essence verte -> Jauge de charge jaune (100-60), orange (60-30), rouge (30-0)
- [x] Tablette New Garray adaptée aux véhicules éléctriques

### Station essence
- [x] 100 Litres -> 60 kWh

### UPW
- [x] Portage soz-core du menu
- [x] Possibilité pour un employé de mettre en halo les endroits précis ou peuvent être installées les bornes.
- [x] Ajout des blips sur la carte pour les positions des bornes à placer (si option précédente activée)
- [x] Possibilité de commander des véhicules électriques comme NW. Menu exhaustif basé sur BDD. 1% du prix. Permission entreprise incluse.
- [x] Shop patron et menu de commande de véhicule

## Condition véhicule
- [x] Capacité du réservoir 100L -> 60kWh
- [x] Consommation du véhicule divisée par 3
- [x] Usure de la batterie divisée par 3
- [x] Suppression de la feature du réservoir d'essence qui fuit pour les voitures électriques

## Batterie électrique de voiture
- [x] Batterie du véhicule à acheter et changer par UPW
- [x] Il est impossible de changer l'huile d'une voiture électrique.
- [x] Même pénalité, mécanique que le réservoir d'huile des voitures thermiques
- [x] Batterie vide donnée à UPW pour recyclage par BB
- [x] Deux nouveaux items associés : "Batterie lithium-ion" et "Batterie lithium-ion vide" dans le shop patron
- [x] 1 Nouvel item pour recharger une voiture électrique : "Batterie portable" qui recharge de 20/60

## Les bornes de recharge
- [x] Les bornes sont reliées à une station essence
- [x] Les bornes sont placées à des endroits définis, mais doivent être installées.
- [x] Ajout de la possibilité de poser une borne pour les employés d'UPW
- [x] Texture dynamique en fonction de la charge de la borne
- [x] Nouvel item associé : "Borne de recharge" dans le shop patron
- [x] Les bornes existent en BDD et ont un stockage de 600 kWh
- [x] Possibilité pour un employé d'UPW de recharger les bornes (40,30,20 kWh pour fossile,hydro,éolienne)
- [x] Rechargement des véhicules électriques uniquement, à une vitesse divisée par 3.
- [x] Il est impossible de mettre de l'essence dans une voiture électrique, et d'électricité dans une voiture thermique.
- [x] Nouvelle animation de "prendre la prise"
- [x] Nouveau sound design pour le rechargement
- [x] Nouveau prop "prise"
- [x] BTarget l'arriere du véhicule pour pouvoir le recharger

## Concess électrique
- [x] Pnj qui donne accès au catalogue électrique.
- [x] Voitures d'exposition dans le concess éléctrique

### Why would this feature be useful?

C'est super cool ! Et ça roule vite aussi

**Comment by NariieL** [comment]
It's been a while since this was listed on the patch note, thanks again. <3
