### ISSUE TITLE
[Inventory] Adding object transfer shortcuts

### ISSUE THREAD

**Issue by Moustash** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

Inventory

### Explain the current situation that you do not think is right.

You actually must drag and drop items from an inventory to another with your mouse, and have to change the quantity each time.

### How is the improvement you propose?

- Adsing a shortcut to move **Specific number** like **ALT + DRAG**
- Adding a shortcut to move **ONE item of the stack** like **CTRL + Drag**
- Adding a shortcut to move **maximum possible weight of a stack** like **DRAG & drop**

**Comment by NariieL** [comment]
Hello ! Good for us, if u want working on it. <3

**Comment by Moustash** [comment]
# How it's going ?

## Keyboard Shortcut on drag

- [x] DEFAULT -> Totallity (or possible)
- [x] CTRL  -> 1 
- [x] ALT  -> Input with half by default

https://user-images.githubusercontent.com/38319075/219872179-915003e7-f7d2-4f0a-9146-0b5dbc4dfb47.mp4

**Comment by Zocaxu** [comment]
Coucou @Moustash
Implémenter un "transfert auto" sur la base de la quantité max possible est vraiment intéressant, surtout pour certaines entreprises ou les joueurs transferent des gros volumes en permanence. Je pense qu'elle a sa place sur SOZ !

Voila comment je l'implémenterais :

Ton NUI connait les capacités et les états des deux inventaires, autant l'utiliser
Dans `resources\[soz]\soz-inventory\ui\src\components\Container\Storage\StorageContainer.tsx`,  éditer ton appel à `transferItem` comme suit
```tsx
            const sourceInvId = event.active.data.current.container === 'player' ? playerInventory?.id : targetInventory?.id;
            const targetInvId = event.over.data.current.container === 'player' ? playerInventory?.id : targetInventory?.id;
            const targetMaxWeight = event.over.data.current.container === 'player' ? playerInventory?.maxWeight : targetInventory?.maxWeight;
            const targetCurrentWeight = event.over.data.current.container === 'player' ? playerInventory?.weight : targetInventory?.weight;

             fetch(`https://soz-inventory/transfertItem`, {
                 method: "POST",
                 headers: {
                     "Content-Type": "application/json; charset=UTF-8",
                 },
                 body: JSON.stringify({
                     source: sourceInvId,
                     target: targetInvId,
                     targetMaxWeight: targetMaxWeight,
                     targetCurrentWeight: targetCurrentWeight,
                     item: event.active.data.current.item,
                     slot: event.over.data.current.slot,
                 }),
             })
                 .then((res) => res.json())
                 .then((transfert) => handleInventoryUpdate(transfert));
```

de sorte que tu récupères ces données dans
`resources\[soz]\soz-inventory\client\main.lua`
comme ceci par exemple
```lua
RegisterNUICallback("transfertItem", function(data, cb)
    local amount = tonumber(data.item.amount)
    local targetMaxWeight = tonumber(data.targetMaxWeight)
    local targetCurrentWeight = tonumber(data.targetCurrentWeight)
    
    local maxAmount = math.floor((targetMaxWeight - targetCurrentWeight) / QBCore.Shared.Items[data.item.name].weight)

    amount = math.min(amount, maxAmount)

    if amount <= 0 then
        exports["soz-hud"]:DrawNotification("Cet inventaire est déjà plein", "error")
        cb({status = false})
        return
    end

    QBCore.Functions.TriggerCallback("inventory:server:TransfertItem", function(success, reason, invSource, invTarget)
        cb({status = success, sourceInventory = invSource, targetInventory = invTarget})
        if not success then
            exports["soz-hud"]:DrawNotification(Config.ErrorMessage[reason], "error")
        elseif success and (invSource.type == "bin" or invTarget.type == "bin") then
            QBCore.Functions.RequestAnimDict("missfbi4prepp1")
            TaskPlayAnim(PlayerPedId(), "missfbi4prepp1", "_bag_pickup_garbage_man", 6.0, -6.0, 2500, 49, 0, 1, 1, 0)
            PlaySoundFrontend(-1, "Collect_Pickup", "DLC_IE_PL_Player_Sounds", true)
        end
    end, data.source, data.target, data.item.name, (amount) or 0, data.item.metadata, data.item.slot, data.slot)
end)
```

Voila ce que ça donne en jeu

https://user-images.githubusercontent.com/72206163/219866791-9d1f892e-bbd3-4f06-ac5e-3837ccb0722f.mp4

Il faut bien sûr que tu édites avec tes propres modifs pour CTRL et ALT.

En espérant avoir aidé, je suis dispo pour questions si tu en as

**Comment by Moustash** [comment]
Merci pour ton aide, c'est terminé :) 

J'y ai ajouté une notification "Info" pour indiquer la quantité déplacée.

https://user-images.githubusercontent.com/38319075/219872179-915003e7-f7d2-4f0a-9146-0b5dbc4dfb47.mp4

**Comment by Zocaxu** [comment]
Est-ce que l'info s'affiche uniquement lorsque la quantité déplacée n'est pas égale à la quantité maximale déplaçable ? Ca serait bien de pas avoir de notif inutile si tout le stack a bien été déplacé

**Comment by Moustash** [comment]
C'est le cas, la quantité déplacée ne s'affiche que si la quantité finale n'est pas égale à la quantité initiale.
