### ISSUE TITLE
[Shops] Migration de soz-shop vers soz-core

### ISSUE THREAD

**Issue by Zocaxu** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

Magasins

### Explain the current situation that you do not think is right.

La ressource soz-shops gérant les magasins de SOZ est écrite en Lua et n'est pas intégrée à notre soz-core chéri.

### How is the improvement you propose?

Portage de soz-shop vers soz-core sans modifier aucune feature pour le moment.
Il en suivra : amélioration de l'HUD et de sa réactivité, optimisation des requêtes client-serveur et serveur-BDD, uniformisation du HUD avec les autres menus soz-core.

## Développement : Terminé

**Comment by NariieL** [comment]
Coucou ! Validé par Brouznouf, on gagnera beaucoup derrière en virant le LUA.
