### ISSUE TITLE
[SOZ-PHONE] Display when a society message is anonymous.

### ISSUE THREAD

**Issue by BeaulieuAdrien** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Display when a society message is anonymous.

### Explain all the steps and mechanics clearly and precisely.

When the incoming message is anonymous, a little text will appear above that indicate "Anonyme".

Dark mode :
![image](https://user-images.githubusercontent.com/96381087/219695749-05ad69f2-1730-4dab-9b36-0ae9d62c5490.png)

Light mode :
![image](https://user-images.githubusercontent.com/96381087/219696002-b1f8b129-2638-407a-942e-1b959573f843.png)

### Why would this feature be useful?

This will help the players to know if a message is anonym without having to click on it.

**Comment by NariieL** [comment]
We are totally for it! Thanks to you, you can link a PR there! <3

**Comment by BeaulieuAdrien** [comment]
> We are totally for it! Thanks to you, you can link a PR there! <3

Here is the PR : #133  :)
