### ISSUE TITLE
[Module Shops] Plus de personnalisation personnage

### ISSUE THREAD

**Issue by Zocaxu** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Je propose d'ajouter plus de personnalisation de personnage dans SOZ.

### Explain all the steps and mechanics clearly and precisely.

# [Module] Plus De Personnalisation

Le but de ce petit module, essentiellement data-orienté, est d'ajouter plus de personnalisation disponible pour les joueurs.
Il s'appuie sur l'issue #117, qui me permet de gérer beaucoup plus facilement les magasins de SOZ. Tout est natif à FiveM, et je n'utiliserai aucun mod ou pack.
Ce module comprend les ajouts/modifications suivantes :

### Magasins de vêtement

- [x] Ajout de plusieurs **hauts** dans les bincos/suburban/ponsonbys, allant des manteaux (ouverts et fermés) aux T-shirts en passant par les chemises et les robes.
- [x] Ajout d'une couche de vêtement appelée 'Sous-vêtements' pour les hauts 'ouverts' type manteaux ou vestes ouvertes. Cette couche s'appelle *Undershirts* et est native à FiveM. Elle permet de mettre quelque chose (un tshirt, une chemise, etc...) sous sa veste ou son manteau.
- [x] Ajout des gants pour tous les personnages.
- [x] Ajout de plus de modèles et plus de couleurs de sac.
- [x] Ajout des cravates et des noeuds papillons pour les vêtements compatibles (Ajouté à la bijouterie).

### Bijoutier

- [x] Ajout des accessoires : colliers, chaines, écharpes, bandeaux, etc...

## Ajouts pour FFS

- [x] Ajout de nouveaux crafts et items pour restocker les gants.
- [x] Ajout d'un nouveau craft et item pour restocker les sacs
- [x] Ajout de nouveaux crafts et items pour restocker les sous-vêtements.

# Bugs/issues corrigés par le module

- #5 
- #64 
- #59

# Développement : TERMINÉ (Attente review et tests)

### Why would this feature be useful?

Je trouve personnellement que SOZ manque vraiment de personnalisation personnage. C'est un élément non essentiel mais qui apporte énormément d'immersion et de plaisir pour les joueurs.
Je pense que ces ajouts permettront aux joueurs de créer le personnage de leur rêve !

**Comment by NariieL** [comment]
Hello ! Insane. <3

**Comment by Zocaxu** [comment]
Démo pour les gants

https://user-images.githubusercontent.com/72206163/222149657-0508d314-564b-4c38-b40a-deb9faaa7698.mp4

Les données pour les gants, si des gens veulent y jeter un oeil

[GANTS V2 MIGRATION.csv](https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/files/10861390/GANTS.V2.MIGRATION.csv)

**Comment by Zocaxu** [comment]
Demo pour les colliers et accessoires

https://user-images.githubusercontent.com/72206163/222152643-29dbf106-fd71-4fff-8e03-04d4c0951864.mp4

**Comment by Zocaxu** [comment]
A la vue de la quantité de vêtements qui seront disponible, je propose de modifier légèrement la manière dont les vêtements sont restockés :
- Au lieu de restocker 10 vêtements d'un modèle, puis 10 d'un autre, etc... faire des boucles de 5 en 5 au lieu de 10 en 10.

Un exemple étant plus parlant :
- Alice Douce souhaite restocker le Ponsonbys. Elle dispose de 30 hauts luxueux sur elle.
- Alice restocke les vêtements, mais au lieu de pouvoir faire 3 loops de 10 vêtements qui feront donc +10 à 3 vêtements différents, elle peut désormais faire 6 loops de 5 vêtements et fera donc +5 à 6 vêtements différents.

Objectif : augmenter la diversité des vêtements qui seront restockés à chaque fois, en partant du principe que les joueurs voudront avoir plus de choix à leur disposition.

**Comment by Zocaxu** [comment]
Développement terminé, en attente review et tests

**Comment by NariieL** [comment]
Already merged. <3
