### ISSUE TITLE
[Téléphone] Payer ou refuser les factures/amendes via le téléphone

### ISSUE THREAD

**Issue by Kedrihan** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

Téléphone

### Explain the current situation that you do not think is right.

Actuellement, nous devons passer par le menu F1 pour payer ou refuser les factures/amendes qui ne le sont pas immédiatement après émission.
Je trouve que cela n'est pas très RP.

### How is the improvement you propose?

Je suggère de passer le payement et le refus des factures/amendes en attente sur une application du téléphone, afin que ce soit + RP d'effectuer cette action.

**Comment by NariieL** [comment]
Ola ! Si tu veux bosser dessus, on est ok, je trouve ce changement plus que sympa !

**Comment by Kedrihan** [comment]
Super ! Ce week-end ça sera dans une PR 👀

**Comment by Kedrihan** [comment]
La PR est dispo (#125)

Comme indiqué dedans, je suis resté au plus simple dans le fonctionnement.
Je suis prêt à y consacrer plus de temps si en effet la migration complète de la gestion des factures dans le téléphone vous semble être une bonne idée niveau Staff.
Si en effet cela est envisageable, j'ignore s'il serait pertinent au niveau du code d'avoir la feature de paiement instantanée avec Y ou N dans le code du téléphone.

Également avec cette migration, et je viens d'y penser, il serait aussi possible de diviser l'application Factures en 2 onglets, un avec les factures reçues comme dans la PR, l'autre avec un suivi des factures émises par le joueur des X derniers jours par exemple pour savoir si elles sont payées, refusées, ou en attente (voir non affichées si payées pour limiter la quantité ?).
Qu'en pensez-vous ?
