### ISSUE TITLE
[LSMC] Btarget HP

### ISSUE THREAD

**Issue by Maskowh** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Btarget d'auscultation permettant de connaître les HP de la cible

### Explain all the steps and mechanics clearly and precisely.

BTarget Auscultation indiquant au bout d'une animation l'état de la santé du patient en Notification

### Why would this feature be useful?

Je trouve que les "Vous avez mal à combien sur une échelle de 1 à 10", nécessaires pour que les médecins puissent appliquer le bon nombre de soins, sont peu immersifs et pas forcément en cohérence avec les circonstances de l'accident.

Cette feature permettrait de se concentrer sur le dialogue patient/médecin, tout en permettant de vérifier l'état des HP du patient pour contrôler / utiliser le bon nombre de soin

**Comment by NariieL** [comment]
Nous sommes contre ! Il faudrait que les HPs s'ajoutent à une information qui existe déjà.
