### ISSUE TITLE
[Vehicles] Detect proper ped position to enter corresponding door.

### ISSUE THREAD

**Issue by poulpito** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

Vehicle / soz-core 

### Explain the current situation that you do not think is right.

Today, the position of the ped is calculated for a pre-determined vehicle bone list based on either the door or the vehicle seat. 

The problem of iterating this complete list is that the detection of the rear door is done at the hinge (by car design), 
so that a ped between the front door and the rear door will always enter the rear door. 
The ped is required to be placed towards the front mirror to enter the front door.

### How is the improvement you propose?

My suggestion is to change the vehicle bone list to use only the door handles ( for all vehicles 2 and 4 seats) + keep the rear wheels for places 5 and 6 (dubsta3 or brickade).
In the case of motorcycles, the code does not intervene and the ped will always be placed as driver, the second ped as passenger. 

You can see an extract of car file.  For each door, a handle is defined and can be used as reference bone to calculate position

![OpenIV_DsMkV0zdIK](https://user-images.githubusercontent.com/4135866/222607745-134e9881-bef0-4ab7-879e-95c38ca149c7.png)

https://user-images.githubusercontent.com/4135866/222609563-80a095df-8872-4cdd-bbad-49c664c69a08.mp4

**Comment by Zocaxu** [comment]
I’m loving it 🤘
