### ISSUE TITLE
[Définition tenues de service en jeu]

### ISSUE THREAD

**Issue by Maskowh** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Afin de passer la gestion des tenues de service complètement en RP, et d'éviter à la fois les demandes par ticket pour ajout/modification et le fait de devoir modifier le code pour modifier une tenue, je propose que l'on puisse le faire en jeu

### Explain all the steps and mechanics clearly and precisely.

Dans l'optique d'intégrer des interactions entre entreprises, j'ai envie d'utiliser le feature #73 pour que FFS soit impliqué, mais je vais également proposer une alternative.

A partir d'une tenue confectionnée par FFS en Item (ou de le tenue portée actuellement en alternative), le Patron (ou l'employé bénéficiant d'une permission créée pour l'occasion), peut la définir comme tenue de service, en saisissant un nom.

Implique de stocker en base les tenues définies ainsi.

### Why would this feature be useful?

- Eviter les tickets pour ça
- Eviter d'avoir à modifier les sources (et donc attendre une release) pour modifier une tenue
- Rendre le serveur plus "portable": chaque serveur peut avoir ses propres tenues

**Comment by DreamXZE** [comment]
J'aime beaucoup l'idée, et si l'accord est donnée pour utiliser #73 , je serais dispos pour t'expliquer au besoin comment sont stockées les données des vêtements 🙏

**Comment by NariieL** [comment]
Excellente idée ! Nous sommes pour. Tu peux bosser ça, même si je risque de modifier pas mal de choses si c'est trop "Simple et gratuit" de modifier une tenue entreprise. Pense à y ajouter un coût et restriction.

**Comment by Maskowh** [comment]
Ok, je vais bosser dessus.
Au niveau du coût, je pense que c'est à voir en RP entre FFS et les entreprises.
Au niveau de la restriction, j'avais pas forcément l'idée d'en mettre, mais je peux limiter à un nombre max de tenues de services différentes (6 par exemple?). Cela pourra évoluer si un jour vous décider de mettre des améliorations d'entreprise (stockage, coffre, frigo, vestiaire)

**Comment by f0wlerz** [comment]
Hello! J'ai vu avec Maskowh pour relancer cette issue.

Pour le système de restriction / rendre la modification de tenue coûteuse, est-ce que ça vous irait si on mettait en place un item cintre que la direction de FFS pourrait acheter et qui serait consommé lors de l'ajout d'une tenue ? De cette manière on peut mettre un prix conséquent sur l'item pour que ce soit à minima pas gratuit de changer de tenues tous les deux jours.

Pour l'idée de la limitation du nombre de tenues on peut facilement caper à 5 ou 6 le nombre de tenues (par sexe) de chaque entreprise c'est pas gênant.

Afin que ce soit modifié dès l'ajout de la tenue et non pas au reboot le lendemain il va falloir qu'on mette stocke les tenues entreprises en db dans une table type job_cloakroom, seriez-vous ok avec cela ?

**Comment by Maskowh** [comment]
Repris dans l'issue #271 , je cloture.
