### ISSUE TITLE
[Logement] Pouvoir renommer une tenue sans la supprimer et la recréer

### ISSUE THREAD

**Issue by Kedrihan** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

Logement

### Explain the current situation that you do not think is right.

Actuellement, si on souhaite renommer une tenue dans notre logement, on doit la supprimer pour la recréer avec le nouveau nom. Ce n'est pas très pratique

### How is the improvement you propose?

L'amélioration que je compte réaliser consiste à rajouter une option "Renommer" dans le menu déroulant avec "Se changer" et "Supprimer" afin de pouvoir renommer la tenue sans devoir la supprimer et la recréer.

**Comment by NariieL** [comment]
Banger absolu.
