### ISSUE TITLE
Pouvoir voir le prix de l'essence à la pompe

### ISSUE THREAD

**Issue by Kedrihan** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Pouvoir voir le prix de l'essence à la pompe avant de faire le plein.

### Explain all the steps and mechanics clearly and precisely.

Ajouter un Btarget aux pompes à essences afin de pouvoir consulter le prix de l'essence au litre.
(A étendre aux bornes des véhicules électriques avec le module dédié)

### Why would this feature be useful?

Cela permettrait aux joueurs de pouvoir consulter le prix de l'essence en amont de leur plein, au lieu de le constater après coup et en calculant. 
Plus de joueurs pourront du coup se rendre compte du prix de l'essence in game (car pas de calcul à faire) et potentiellement créer du RP autour de ça.

**Comment by NariieL** [comment]
Ola! Thank you for the proposal, it is accepted.
