### ISSUE TITLE
Prix qui sort du rectangle lors d'un plein de plus de 100$

### ISSUE THREAD

**Issue by MimiBloops** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of Issue

Lorsque qu'on fait un plein en station qui dépasse les 100$, le prix sort un petit peu du rectangle d'information.
![prix essence](https://user-images.githubusercontent.com/14274835/225328894-58244bda-3ad4-4f8c-932a-7652df095d87.png)

### Expected Behavior

Que le prix ne dépasse pas du rectangle.

### Reproduction Steps

Faire un plein suffisamment grand pour qu'il coute plus de 100$.

### Does it happen all the time ?

Oui.

**Comment by NariieL** [comment]
Tu peux faire ta PR pour ! <3

**Comment by MimiBloops** [comment]
Ceci a été fix par Zo dans le module électrique. :)
