### ISSUE TITLE
Application téléphone "Giphy"

### ISSUE THREAD

**Issue by GCainjo** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#139]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What feature are you suggesting?

J'ai pu remarquer que les gifs sont pas mal utilisé dans les messages, cependant les joueurs doivent quitter le jeu afin de trouver et copier l'URL du gif. Je propose donc d'ajouter une application de gifs directement sur le téléphone des joueurs.

A l'entrée sur l'application, nous retrouverions les gifs en tendance du moment avec un champ de recherche. Lorsque l'on écrit dans ce champ, une requête est effectuée via l'API de Giphy afin d'afficher les gifs en rapport avec la recherche.
Le joueur peut alors cliquer sur le gif choisit, ce dernier s'affiche alors en plus grand avec un bouton permettant de copier dans le presse-papier l'URL du gif que le joueur pourra coller dans un message.

### Explain all the steps and mechanics clearly and precisely.

Pour réaliser cela, Giphy propose via leur api de récupérer les gifs et via leur SDK des mises en pages rapide sous ReactJS grâce à différents paquets NPM notamment [@giphy/react-components](https://www.npmjs.com/package/@giphy/react-components) et [@giphy/js-fetch-api](https://www.npmjs.com/package/@giphy/js-fetch-api).

Pour avoir accès à l'API, il suffit d'avoir un compte développeur sur le site [developper.giphy.com](https://developers.giphy.com/)

### Why would this feature be useful?

Cette fonctionnalité va permettre d'accéder aux gifs sans avoir à quitter le jeu, ce qui va améliorer l'expérience du joueur

https://user-images.githubusercontent.com/37529274/228196214-765f25eb-16b9-4985-be5c-ed28b801f665.mp4

**Comment by NariieL** [comment]
Hello ! On ne souhaite pas ajouter une application lié au .Gif, ils sont tolérés mais pas plus. Merci tout de même à toi pour la proposition. <3
