### ISSUE TITLE
[Tenues FDO] Améliorations diverses

### ISSUE THREAD

**Issue by Kedrihan** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#150]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

Tenues LSPD & BCSO

### Explain the current situation that you do not think is right.

Plusieurs points : 
- Les tenues de service homme LSPD et BCSO n'ont pas les logo sur les 2 manches contrairement aux femmes
- La tenue Hiver LSPD n'a rien sous la veste
- Hors tenue moto et Hiver, LSPD et BCSO n'ont pas de tenue manches longues
- Le LSPD n'a pas d'équivalent au chapeau du BCSO
- Les tenues de moto femme n'ont pas de gants contrairement aux hommes

### How is the improvement you propose?

Toutes ces modifications sont pour les tenues homme et femme, sauf si le contraire est précisé.

Point par point : 
- Correction du haut des tenues de service homme LSPD et BCSO pour avoir le logo sur les 2 manches + modification texture LSPD homme pour avoir les 2 logos dessus

- Correction de la tenue Hiver LSPD pour avoir quelque chose en dessous + modif couleurs texture pour ne plus avoir la cravate bleue
![image](https://user-images.githubusercontent.com/20105314/228786098-21fcd4fe-686e-4452-9de9-a47daf2808fe.png)

- Ajout d'une tenue manches longues LSPD et BCSO (avec grades affichés)
![image](https://user-images.githubusercontent.com/20105314/228845836-17c9818d-9e5c-45ef-8f69-2bf35816c582.png)

- Ajout d'une texture de casquette pour le LSPD marquée POLICE et mise avec la tenue de service manche courtes, manche longues, et la tenue Hiver
![image](https://user-images.githubusercontent.com/20105314/228845689-fe7199e4-db3b-481b-bb8f-53cf403506ae.png)

- Changement du Torse sur les tenues de moto femme pour y rajouter les même gants que les hommes

Les changements sont déjà développés sur mon fork, mais je peux sans soucis en enlever selon ce qui sera accepté ou non.

Tout ces éléments, si acceptés, pourront en plus être amenés en RP avec un dialogue entre FDO et FFS :)

**Comment by NariieL** [comment]
Les tenues de service homme LSPD et BCSO n'ont pas les logo sur les 2 manches contrairement aux femmes
> Le fait qu'il y ait un seul logo soit voulu, c'est plutôt qu'il y en ait deux qui n'est pas voulu.

La tenue Hiver LSPD n'a rien sous la veste
> Très cool ça !

Hors tenue moto et Hiver, LSPD et BCSO n'ont pas de tenue manches longues
> C'est volontaire, à retirer de la PR.

Le LSPD n'a pas d'équivalent au chapeau du BCSO
> Bonne idée !

Les tenues de moto femme n'ont pas de gants contrairement aux hommes
> Bonne idée !

**Comment by Kedrihan** [comment]
Je modifie la PR pour prendre en compte ces retours !

Je vais aussi enlever le 2ème logo sur les tenues femmes dans ce cas.

**Comment by NariieL** [comment]
Top merciiiiiiiii.

**Comment by Kedrihan** [comment]
Est-ce que tu souhaites que je vire aussi un logo sur toutes les autres tenues qui en ont 2 ou juste sur les tenues de service basiques ?

**Comment by NariieL** [comment]
> Est-ce que tu souhaites que je vire aussi un logo sur toutes les autres tenues qui en ont 2 ou juste sur les tenues de service basiques ?

Juste sur les tenues de services basiques !

**Comment by Kedrihan** [comment]
Ce soir je rouvre ma PR avec les changements du coup !
