### ISSUE TITLE
[Animation] Adapter le prop à la nourriture/boisson utilisée

### ISSUE THREAD

**Issue by Zocaxu** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Utiliser un prop plus adapté à la nourriture/boisson utilisée par le joueur lorsque c'est possible.

### Explain all the steps and mechanics clearly and precisely.

Au lieu d'afficher systématiquement une bouteille d'eau ou un burger pour la boisson et la nourriture, utiliser d'autres props pour mieux correspondre à l'item utilisé. J'utilise les props natifs à GTA au plus possible. Le fromage/saucisse/grappe de raisin seront probablement des props customs faites pour SOZ car ils n'existent pas en natif.

### Quelques exemples :

Bouteille d'alcool :
<img src="https://user-images.githubusercontent.com/72206163/229110104-9ec790ec-615b-4e8c-94fa-e0bed92dc799.png" width="200" height="200">
Vin :
<img src="https://user-images.githubusercontent.com/72206163/229110127-7780121a-f781-4e4e-bd86-babd8fa09fa3.png" width="200" height="200">
Cocktail :
<img src="https://user-images.githubusercontent.com/72206163/229110141-54aa56de-3cb4-4ae1-9c6d-e43a59883adf.png" width="200" height="200">
Sandwich :
<img src="https://user-images.githubusercontent.com/72206163/229110156-19f4cab4-c6a9-4660-9c23-8fda3f11f8a3.png" width="200" height="200">
Café :
<img src="https://user-images.githubusercontent.com/72206163/229110171-bd5ccf09-110c-463e-9c0b-a122a5574f4f.png" width="200" height="200">

### Why would this feature be useful?

Ajouter plus d'immersion en jeu

**Comment by NariieL** [comment]
Omgé nice.

**Comment by Rigonkmalk** [comment]
Et il est où mon fromage ? 🧀

**Comment by Zocaxu** [comment]
Il est là. Il arrive fort.

**Comment by Zocaxu** [comment]
Démo des props ajoutés (je n'ai pas fait toutes les bouteilles d'alcool, de vin, et les cocktails mais ils sont ajoutés)
https://user-images.githubusercontent.com/72206163/230378717-ea26d580-151b-4157-88e5-ec57576bb09e.mp4
