### ISSUE TITLE
[Dispenser] Display item price

### ISSUE THREAD

**Issue by lucaslg** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

soz-utils / Dispenser

### Explain the current situation that you do not think is right.

Today, when interacting with a dispenser (coffee, water bottle...), we have no idea how much what we'll be buying will cost. There is also no mention of cost in the notification when buying the item, so the player need to do a subtraction before-after to know how much it cost.

### How is the improvement you propose?

Proposed improvment consist of displaying the cost of the item in the btarget menu, see screenshot below:
![image](https://user-images.githubusercontent.com/8122362/229800021-740a365e-2fb0-41ae-96f1-c05219cce458.png)

**Comment by NariieL** [comment]
Merciii ! On ajoute ça asap. <3
