### ISSUE TITLE
[LSMC] Mise à jour de la carte de santé

### ISSUE THREAD

**Issue by LarryCooperSOZ** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

LSMC | Carte de santé

### Explain the current situation that you do not think is right.

La carte de santé n'a pas été mise à jour suite au changement de logo du LSMC

### How is the improvement you propose?

[Voici un proposition de mise à jour de la carte de santé avec les nouvelles couleurs du LSMC](https://cdn.discordapp.com/attachments/976084543331262494/1092847944325144606/LSMC_carte_sante.png)

![LSMC_carte_sante](https://user-images.githubusercontent.com/120988467/229857141-7bbcec74-2a59-41bb-bc34-467e44558142.png)

**Comment by NariieL** [comment]
Nous sommes pour ! 🏩
