### ISSUE TITLE
[Animation] Difference in position related to animation.

### ISSUE THREAD

**Issue by NariieL** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#16]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of Issue

When I lie on the operating table, I see my character under the table, while the doctor sees me on the table.
![image](https://user-images.githubusercontent.com/104008465/208459295-826e2863-34a2-4a5e-9ee0-c1361ee5ada8.png)

### Expected Behavior

Everyone, including me, should see me on the operating table.

### Reproduction Steps

I lie on the table, and depending on the timing, I sometimes end up under it.

### Does it happen all the time ?

Not all the time, but often.

**Comment by Zocaxu** [comment]
J'ai trouvé un fix pour ce problème =>lorsque la personne BTarget la table, TP le personnage légèrement au dessus de la table et le laisser tomber (visuellement quasi invisible) et pas exactement sur la table.
Ca fix le problème _pour les joueurs autour du patient_. Le joueur sur la table et les joueurs présents autour de l'animation voient alors correctement le joueur sur la table. PR #52 

En revanche, je n'ai pas trouvé de fix pour le problème relatif à l'issue #18.
Le problème étant le suivant selon moi et @Alithegood :
Lorsque le spectateur s'écarte de la table d'opération, celle-ci dépop pour le client du spectateur. En revanche l'avatar du joueur ne depop pas et tombe donc par terre logiquement. Si le spectateur revient dans la salle, la table repop pour son client, mais elle pop alors sur le joueur qui est allongé par terre pour son client, d'où ce bug visuel pour les personnes qui déchargent la table dans leur client. Ce bug arrive 100% du temps si la table depop pour le client.
Un fix possible -> Forcer la position du joueur allongé sur TOUS les clients connectés au serveur, ou alors ceux qui sont assez proches du joueur allongé. Cela peut être fait en désactivant la gravité du ped allongé, mais ça doit être fait par tous les clients. C'est beaucoup de transferts d'infos pour juste une personne allongée, à vous de voir.

**Comment by NariieL** [comment]
Merciiii. <3 Disponible dans la prochaine note de patch.

**Comment by NariieL** [comment]
![image](https://user-images.githubusercontent.com/104008465/213827967-30e79368-1233-4f13-bb06-451d8e379992.png)
Pas fix finalement !

**Comment by Zocaxu** [comment]
Coucou !
Comme j'ai dit juste avant, effectivement le bug n'est pas complètement fix. Pour les gens qui viennent de loin et observe le patient a posteriori, je n'ai pas de fix... désolé ;(
