### ISSUE TITLE
Nouvelles options du limiteur de vitesse

### ISSUE THREAD

**Issue by lucaslg** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

Vehicule / soz-core

### Explain the current situation that you do not think is right.

Le limiteur de vitesse actuel propose des vitesses pré-définies ne permettant pas de, par exemple :
- se caler sur la vitesse des PNJ pour se fondre dans la masse
- limiter sa vitesse à 160 km/h pour éviter de déclencher la mécanique de stress

### How is the improvement you propose?

Ajout d'une option "Limiter à la vitesse actuelle" qui donnera au joueur plus de contrôle sur le limiteur de vitesse. 
Et
Ajout d'une option "Limiter la vitesse à ..." ouvrant une boite de dialogue qui permet d'entrer manuellement la vitesse du limiteur

**Comment by NariieL** [comment]
Nous sommes pour ! Merci de la PR, on s'en occupe asap.
