### ISSUE TITLE
[Phone] Répondeur entreprise : Supression du point GPS

### ISSUE THREAD

**Issue by Moustash** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Ajouter un bouton pour supprimer le point GPS sans avoir à retourner dans le menu principal du jeu.

### Explain all the steps and mechanics clearly and precisely.

Le bouton supprime simplement le waypoint du GPS.

https://user-images.githubusercontent.com/38319075/230511956-78961eb4-3ba7-4107-b1f8-df7fa5d6b648.mp4

### Why would this feature be useful?

Tout les métiers où les appels en voitures peuvent être récurrents sont impactés et cela faciliterait la tâche des usagers.

**Comment by NariieL** [comment]
Nous sommes pour ! <3
