### ISSUE TITLE
[Animation] Ajout de la demarche par defaut pour chaque genre.

### ISSUE THREAD

**Issue by Nelenyaa** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

Animation

### Explain the current situation that you do not think is right.

Actuellement, seul un bouton avec la démarche par defaut du ped associé est disponible.

### How is the improvement you propose?

Remplacer le bouton "Demarche par defaut" par deux nouveau bouton "Demarche par defaut Homme" et "Demarche par defaut Femme" afin de proposer une nouvelle demarche pour chaque ped.

![walk](https://user-images.githubusercontent.com/15704994/230730481-7f8fc8d2-00d6-4a65-ba68-5a91c6ca9675.PNG)

**Comment by NariieL** [comment]
Merciiii ! On ajoute ça dès que possible, c'est validé.
