### ISSUE TITLE
[New Player Loading] Sky cam freeze

### ISSUE THREAD

**Issue by DarkEag** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#17]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

Camera control

### Explain the current situation that you do not think is right.

The camera can be moved when you first log in for a new player and after selected the location and it is super weird.

### How is the improvement you propose?

Stops the ability to move the camera all arround while the camera zooms to the ground.
I have done the "[Improvement] Sky cam freeze #15" pull request with the proposed solution. Thanks !

**Comment by NariieL** [comment]
Thanks for your contribution. <3 Merge in https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/commit/624707f11f505b2a8cbefa9155f846a09cdf00f8
