### ISSUE TITLE
[OSS] EOL in .prettierrc

### ISSUE THREAD

**Issue by Zocaxu** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

OSS

### Explain the current situation that you do not think is right.

Le `endOfLine` dans le .prettierrc est set à `lf` ce qui fonctionne sur Linux mais pas sur Windows.
Pour éviter de devoir jongler entre les EOL des deux systèmes, je propose de le set à `auto` qui s'adapte au système.
En pratique ça ne change rien, mais c'est plus confortable pour le dev.

### How is the improvement you propose?

Plus de confort pour les devs Windows

**Comment by joelwurtz** [comment]
Sorry would not accept this, you can configure your ide for this project to handle only lf, i don't want mixed new line in our files
