### ISSUE TITLE
Avoir accès aux employés actuellement en service depuis l'entreprise.

### ISSUE THREAD

**Issue by DreamXZE** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#174]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Je suggère que depuis l'ordinateur de prise de service, une personne en service (avec l'autorisation nécessaire au niveau des grade de l'entreprise) puisse voir qui est actuellement en service.

### Explain all the steps and mechanics clearly and precisely.

L'ajout serait via un B-target sur l'ordinateur de prise de service. Cela ouvrirai un liste de nom de personne en service.

Toute personne hors service (connecté ou non) ne sont pas présente sur cette liste.

### Why would this feature be useful?

Cela permettrai le retrait du role de service sur les différents discord entreprise et toute la gestion pourrait se faire directement ingame plutot que de devoir prendre son service à deux endroits.

**Comment by NariieL** [comment]
Nous sommes pour ! A voir en pratique.

**Comment by DreamXZE** [comment]
Voici une petite vidéo faite pour l'exemple (ne faites pas attention à l'image FFS alors que nous sommes à PAWL, le menu a été fait rapidement pour l'exemple seulement)

Utilisation du B-target sur l'ordinateur ouvre le menu montrant les nom et prénom des personne en service. Pas d'interaction supplémentaire possible, pas d'autre information possible.

https://user-images.githubusercontent.com/46448950/232172702-c69e665d-5787-4549-9ab9-0a9949b1a5fa.mp4

**Comment by DreamXZE** [comment]
Ajout de la banière qui depend de l'entreprise ✔️ 
Ajout d'un titre au menu ✔️ 
![image](https://user-images.githubusercontent.com/46448950/232242614-a3c25202-ad54-410c-9e20-2c23384fea1e.png)

Ajout de l'autorisation de grade pour avoir accès à la feature ✔️ 
![image](https://user-images.githubusercontent.com/46448950/232242760-6210455c-7698-4db3-a3ef-c8e261e8f47f.png)

Si accès:
![image](https://user-images.githubusercontent.com/46448950/232243959-47faf30a-01eb-4c91-8011-58c626279645.png)

Si pas accès:
![image](https://user-images.githubusercontent.com/46448950/232243066-eefc45eb-bc10-4889-8af9-27635d553a7d.png)

PR associé: https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/pull/177

**Comment by DreamXZE** [comment]
La motivation principale de cette issue reste le retrait des rôles en services sur les différents discord entreprise, et que plus de chose se fasse in RP plutôt que de demander une action en externe 🙏

**Comment by sebastiendeu** [comment]
Pull Request validée et mergée !
