### ISSUE TITLE
[LSMC] Allow Med player to see if patient is full health or not + B-target correction

### ISSUE THREAD

**Issue by poulpito** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

LSMC B-Target  and capacity to have Health indication with existing system

### Explain the current situation that you do not think is right.

When a patient is healed with a medic kit, it only heal 25hp over 200 (max health).  Problem is that medic have no indication of current ped health and if it required 3 or 5 medic kit.  Player can leave hospital paying but having only 3/4th of the health. 

Also small correction : a medic can remove/put back patient clothes without being on duty (b-target active) 

### How is the improvement you propose?

Linked with closed issue #127, you ask for a system embeded in current behavior/menu

Adding a simple notification for the med player (and only the med player)  when a medikit is used 

if patient is not completly healed after a medikit : 
![FiveM_b2802_GTAProcess_Bm75LnOu44](https://user-images.githubusercontent.com/4135866/232228980-af62c4f8-6c3e-4a99-ae55-9fd8296f2562.png)

If patient is fully healed after a medikit : 
![FiveM_b2802_GTAProcess_ODk9RSVbLe](https://user-images.githubusercontent.com/4135866/232229000-98f20513-fa90-4d46-9c64-60ea7b42db8f.png)

For the undress/dress player, simple add of the condition "on.duty" to display b-target ONLY if the medic is on duty 
(like all other medic action, does not seems logical to have this option available off duty as it's only available in hospital coordinates)

Code ready to PR if it's ok.

**Comment by NariieL** [comment]
We will make sure that a Care Kit heals 100%. Therefore, it is not necessary.
