### ISSUE TITLE
[Animation] Improve/Expand animation list & alternative male animation to female

### ISSUE THREAD

**Issue by poulpito** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

animation / soz-personal-menu

### Explain the current situation that you do not think is right.

Not all animations are present (compare to dp-emotes for example) 
and some of the animations/scenario are male only.  

### How is the improvement you propose?

Re-order current animation/name  and add almost all animation for a total of ~300 possible. 

Convert male scenario only to Male + Female animation  for example
Female Cop cannot do the "Circulation" animation. 

Here is an example of conversion  for male & female (prop can be adjust) 
![FiveM_b2802_GTAProcess_GMi3ZiBkq5](https://user-images.githubusercontent.com/4135866/232324607-41884acf-c77d-4214-a6eb-7cb1d9fd6c0b.png)

**Comment by poulpito** [comment]
for example, after a gunfight, animation to crawl within direction choose by player 

![ezgif-5-580849c63e](https://user-images.githubusercontent.com/4135866/232326120-43b1bbfb-252c-49de-b899-eacf5d12ca98.gif)

**Comment by poulpito** [comment]
On hold, need to rework on animation list and migrate it to the new soz-core personal menu.

**Comment by NariieL** [comment]
On hold.
