### ISSUE TITLE
Refactor: Update Native Names for Enhanced Readability and Consistency

### ISSUE THREAD

**Issue by spacevx** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

In the code.

### Explain the current situation that you do not think is right.

In some scripts, the code still had the old GTA native names.

### How is the improvement you propose?

I replaced the old native names with the new ones based on the FiveM documentation.

**Comment by NariieL** [comment]
Ola! Unfortunately, from what Brouznouf told me, this change does not help much. Thanks anyway. <3
