### ISSUE TITLE
[Activity] Fishing

### ISSUE THREAD

**Issue by terrainwax** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#19]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

I suggest to add the ability to fish for the player of the server

### Explain all the steps and mechanics clearly and precisely.

While thinking about this feature, I had in mind that just like the hunting permit, there will be a  need to pass a  fishing permit
The main feature will not just be the fishing but also the species conservation, each water point will have a limit of the number of fishes that can be fished. 
For example if in the Alamo sea you have 25 trouts available for fishing and the limit for them to well reproduce is 6, if you go under 6 species left in the lake it will regenerate more slowly but if you fish all of them it will never regenerate and the BCSO will need to reintroduce some species to sustain the species

It will be the job of the BCSO to keep the water point healthy and to prevent poaching to keep species alive.

For the HUD of the fishing I thought about a fishing "minigame '' similar to the one in New World where you need to manage the fishing well to not break the line and lose your bait. For the bait I thought about the offal of the animals gathered by the hunters.

I will have a more detail doc especially on game design and different species to add

This is just a first draft to see if you are interested about

### Why would this feature be useful?

This feature will add more thinks to do for the citizen and will add more food for diversify the citizen habit

**Comment by NariieL** [comment]
Fishing is an activity planned for DLC 3. If you develop something concrete and usable, some parts can be implemented. It will have to be developed in TypeScript. **Be careful, this does not mean that we will accept what you propose. We already have a vague idea of what we want.** The best solution would be to wait for the DLC to come out, and bring your ideas for improvements.

**Comment by terrainwax** [comment]
What i've seen is in the DLC 3 you want a company of fishing, my idea is more like adding a minigame but this minigame add RP for a lot of people until new things come

**Comment by NariieL** [comment]
The fishery will arrive at the same time as the business, not before.
