### ISSUE TITLE
[Phone] Send a message without contact

### ISSUE THREAD

**Issue by Mcfloy** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

Phone

### Explain the current situation that you do not think is right.

We can't send a message without saving the contact before, which is not ergonomic.

### How is the improvement you propose?

On the phone's numpad, add a button next to the green phone to send a message, if the phone number does not exist just create a contact with the phone number as the name before displaying the page.

**Comment by Vaillp** [comment]
Actualy I have a solution for this with this display :
![image](https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/assets/17344267/01e5f710-1c92-4108-89cc-2a793f382124)

If it's good for you I can try to push my file "...\SOZ-FiveM-Server\resources\[soz]\soz-phone\src\nui\apps\dialer\pages\DialerKeyboard.tsx" here.

With this, no need to create a new contact. It just use the same fonction to send a message than the society-messages app.
The number must be 8 characters long. (like the call button)
And it must be a valid number on the server. (inherited from the "navigate(`/messages/new/${phoneNumber}`)" function)

**Comment by NariieL** [comment]
Accepted. You have the liberty of developing this, thank you. <3 Please use this type of display.
> ![image](https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/assets/104008465/6d40e4e0-1133-45f4-9050-e909b00a8a95)

**Comment by Laikker** [comment]
Merci pour la proposition, ca a été intégré au serveur
