### ISSUE TITLE
[Phone] Weather app

### ISSUE THREAD

**Issue by Mcfloy** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

A weather application on the phone, displaying forecast and a countdown when there's an incoming storm.

### Explain all the steps and mechanics clearly and precisely.

The weather module would generate 4 or 5 weather instructions (would need to be equal to 24 in-game hours) in advance instead of one at a time.
The phone would retrieve the next instructions from the weather module and display icons and perhaps bullshit data like the temperature etc. (by the way temperature could and should influence electric vehicle's battery consumption and also the whole city's consumption)

Before a reboot, the storm is coming, the weather module would put 4 or 5 storm instructions and the phone app would add a red countdown on the top informing citizen to stay safe. 

### Why would this feature be useful?

This adds immersion, a friendly reminder for people that needs to disconnect before a reboot and could lead to other features related to the environment.

**Comment by NariieL** [comment]
Ola ! 🐣 Si tu arrives à réaliser un joli front, on est pour ! L'application est utile au RP.
~Ola! 🐣 If you can create a pretty front for the app, we're all for it! The app is useful for the RP.

**Comment by Mcfloy** [comment]
Hello ! Bonne nouvelle j'ai avancé sur l'app et elle est plus ou moins terminée.

Edit: Je montre l'app sur le menu (elle est dernière, même avec le répondeur entreprise)
![image](https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/assets/10086193/d15ee0cb-6a54-44d3-bad7-06b6fa35e7a7)


Il y a trois thèmes de couleur selon l'heure en jeu, bleu ciel le jour, indigo la nuit, orange entre 6h et 8h et 20h et 21h.
![image](https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/assets/10086193/c38e4bd9-1f93-4a3d-b085-53d986e0dee9)
![image](https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/assets/10086193/9610ead5-e53f-4a37-a102-bc696af9be00)
![image](https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/assets/10086193/41475950-19f0-493c-8022-38869615a1c9)

Côté serveur on calcule désormais 5 météos à la suite plutôt qu'une, les probas n'ont pas été changées et la pollution garde la priorité sur l'ensemble.

Par contre il y a tout un nouveau calcul sur les températures avec des valeurs minimales et maximales initiales par saison ET selon le jour et la nuit. Puis des modificateurs selon la météo choisie, donc on laisse l'aléatoire choisir la température mais normalement ça devrait être cohérent pour qu'il y des moments de chauds et de froids mais aussi des températures moyennes en accord avec le climat de l'île.

Note importante: la température est la même sur toute l'île vu que c'est le serveur qui génère ça une fois pour tout le monde. (Après qui sait dans un futur on pourrait faire un quadrillage de météo et faire changer la météo au client selon la zone mais bon c'est pas le but ici)

Ci-joint le tableau excel que j'ai calculé et que je remettrais dans une doc bien faite.
![image](https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/assets/10086193/6c7090c4-324c-489a-bd87-70bf98124fb4)

Aussi dès que le `/thunder` est lancé ça met à jour l'écran de l'appli avec un message et un timer qui se met à jour en temps réel (*wow mais c'est génial !*)
![image](https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/assets/10086193/6c368bec-2ae1-439f-9c24-d8fcfb274bca)

L'icône affichée est la météo actuelle sur l'île, étant donné que le thunder applique d'abord un "Clearing" -> "Rain" -> "Thunder", l'icône se met à jour toute seule à chaque étape de changement de météo.

Les icônes proviennent de icones8 comme c'était le cas avec les autres features donc c'est harmonisé, j'ai vu qu'il y avait des versions animées sauf que: c'est que en noir sur fond blanc, c'est petit, si j'agrandis ça fait vachement moche.

**Comment by Mcfloy** [comment]
Reste à faire:

- [x] Rebrancher la météo avec la pollution (ça plantait chez moi donc j'avais avancé sans) Edit: bon j'ai un hotfix en attendant que soz-upw soit migré dans le core, le pollution manager ne s'initialize pas assez vite et la génération plante.
- [x] Nettoyer le code avec un coup de lint
- [x] Documenter la création d'une application sur le téléphone
- [ ] Très certainement changer la couleur de fond de l'appli si ça plaît pas...
