### ISSUE TITLE
[Téléphone] Afficher le numéro de téléphone d'un contact quand on est au téléphone avec

### ISSUE THREAD

**Issue by MimiBloops** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

Téléphone

### Explain the current situation that you do not think is right.

Lorsqu'on est au téléphone avec un contact qu'on a enregistré, le téléphone nous affiche le nom du contact, la durée de l'appel et les 2 boutons pour raccrocher et couper le micro.

### How is the improvement you propose?

Rajouter une ligne entre le nom du contact et la durée de l'appel, le numéro de téléphone du correspondant.

**Comment by NariieL** [comment]
Oku pour ça !

**Comment by NariieL** [comment]
C'est mergé depuis un moment ! Merci à toi pour la contribution ❤️
