### ISSUE TITLE
[Bank] Misspelling and display name New Gahray.

### ISSUE THREAD

**Issue by Vincent-Sniteur** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#20]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

Bank system - Misspelling

### Explain the current situation that you do not think is right.

Misspelling and display name for **New Gahray** enterprise, which is obsolete.

### How is the improvement you propose?

Fix spelling mistakes and change Benny's display to New Gahray.

**Comment by joelwurtz** [comment]
Fixed, thanks
