### ISSUE TITLE
[Téléphone] Découper un message trop long en plusieurs messages

### ISSUE THREAD

**Issue by Maskowh** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#210]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

Téléphone

### Explain the current situation that you do not think is right.

Actuellement, un message de plus de 512 caractères (taille de la colonne en base) échoue.

### How is the improvement you propose?

Lorsqu'un message dépasse 512 caractères, plusieurs messages sont envoyés.
Un indicateur sur le nombre de messages qui seront envoyés et le nombre de caractères restants avant qu'un nouveau message soit envoyé.

Les points d'attention sont:
 - un émoji peut être coupé entre deux messages
 - un lien externe trop long, au lieu d'échouer comme avant, sera également coupé

https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/assets/123783610/baf8667a-03db-401c-9186-15539648a388

**Comment by NariieL** [comment]
Sorry, we don't accept this change. <3 However, you can propose a PR that blocks the textbox at 500 characters to avoid problems. Also, if players are going to write such long messages to each other, they might as well call each other when they're free!
