### ISSUE TITLE
[Telephone] Onglet dans l'appli Banque d'historique des virements

### ISSUE THREAD

**Issue by Maskowh** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

Onglet dans l'appli Banque d'historique des virements

### Explain the current situation that you do not think is right.

Bonjour, je refais cette issue car vous avez fermée la #104 par erreur et que je ne peux pas la rouvrir

Ajouter un onglet dans l'appli Banque d'historique des virements: Date, emetteur, recepteur, montant.

A la manière de l'appli "Téléphone", ayant plusieurs onglets en bas de l'appli, avoir deux onglets:

Le premier "Compte", reprenant l'affichage actuel
Un deuxième "Virements" représentant une liste des derniers virements effectués (au cours des 30 derniers jours par exemple). Cela comprend les virements effectués et reçus. L'affichage serait très classique, comme ce qu'il se fait dans l'appli Twitch News ou le répondeur entreprise.

### How is the improvement you propose?

Trace les virements effectués.
Permet d'avoir des preuves d'échanges d'argent, pour des enquêtes par exemple.

**Comment by Maskowh** [comment]
https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/assets/123783610/25d61885-e44c-4f5c-8ade-bd3438cd2be2

**Comment by NariieL** [comment]
Accepted. We'll be taking a closer look very soon. <3

**Comment by Laikker** [comment]
Thanks for the PR but it was added inhouse during the rework of the bank
