### ISSUE TITLE
[Outfit] Delete New Gahray old unused work clothes.

### ISSUE THREAD

**Issue by Vincent-Sniteur** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

Request made to remove outfits that are no longer used in the company's outfit listing.

### Explain the current situation that you do not think is right.

Unused Outfit in RP.

### How is the improvement you propose?

Delete outfit : **chef d'atelier**, **mécano confirmé**, **mécano novice** & **responsable d'atelier**
Rename : **Patron** to **Direction**

**Comment by NariieL** [comment]
Accepted. We'll be taking a closer look very soon. <3
