### ISSUE TITLE
[Phone] - Envoyer message hors-contact

### ISSUE THREAD

**Issue by Maskowh** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

Phone

### Explain the current situation that you do not think is right.

Actuellement, on ne peut pas envoyer un message à un numéro hors-contact (à part depuis le répondeur entreprise).

### How is the improvement you propose?

Ajouter un moyen d'envoyer un message à quelqu'un sans l'avoir dans ses contacts.

Plusieurs propositions:

1. Enrichir l'écran actuel 
![image](https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/assets/123783610/a911fbb1-4ac9-44ec-b63a-b5dbd2b0baff)
Au lieu de la seule liste de contacts comme actuellement, on peut saisir un numéro plus haut.
C'est la solution que j'ai développée instinctivement, mais en voyant le résultat fini, je me dit que c'est peut-être un écran trop chargé.
Epuré un peu, cela donnerait ça 
![image](https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/assets/123783610/5a9b92be-3831-4737-89fe-6919a04543d1)

2. Ajout d'un nouvel écran de composition accessible depuis un nouveau bouton en haut des conversations
![image](https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/assets/123783610/c917cec2-198f-46ab-b6bb-9da9c9524d03)
On rajouterait donc un bouton à coté du "+"
![image](https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/assets/123783610/0f426a25-d2a0-413e-a071-108f56582e1e)
Et on arriverait sur un écran comme celui-ci, mais avec un bouton "Message" au lieu du Téléphone comme de l'image.

3. Un peu la même idée que la 2, mais on garde un seul bouton, qui amène sur l'écran contacts, comme actuellement, sauf que cet écran intègre maintenant le système de NavigationBar de l'application Téléphone (en bas), et permet donc d'accéder à l'écran de composition.
![image](https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/assets/123783610/8d766647-d148-4f43-a833-3346f50a84c8)

Qu'est ce qui vous conviendrait mieux?

**Comment by Maskowh** [comment]
Je viens de m'apercevoir que ça a déjà été proposé sur #190 
Si la solution qu'ils ont proposé convient, on peut fermer cette issue.

**Comment by NariieL** [comment]
Hello ! We're going to accept Mcfloy's PR in relation to yours. Thanks to you for this proposal. <3
