### ISSUE TITLE
[Fouille] Notifier la personne de ce qui lui est pris

### ISSUE THREAD

**Issue by Maskowh** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

Inventaire/Fouille

### Explain the current situation that you do not think is right.

Lorsqu'on est zippé/menotté / fouillé par un FDO les mains levées, et qu'on nous prélève des objets, on ne le sait pas

### How is the improvement you propose?

Rajouter une notification quand un objet nous est prélevé

**Comment by NariieL** [comment]
Accepted. You have the liberty of developing this, thank you. <3 Don't forget to have a visually appealing text with colors and shape.

**Comment by Laikker** [comment]
Integrated during the inventory rework
