### ISSUE TITLE
[Fouille] Inventaire fouillé mélangé

### ISSUE THREAD

**Issue by Maskowh** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

Fouille/Inventaire

### Explain the current situation that you do not think is right.

Lorsque l'on fouille quelqu'un, son inventaire nous apparait tel que la personne l'a rangé.

### How is the improvement you propose?

Je propose d'afficher l'invantaire de la personne fouillée mélangé.
Dans le cas d'une fouille par FDO, cela peut introduire des erreurs et des oublis.
Dans le cas d'une fouille crimi, cela rajoute du stress en plus des erreurs et oubli possible, car c'est souvent sur des cènes déjà stressantes.

**Comment by Zocaxu** [comment]
Est-ce que tu peux faire ça sans que inventaire du joueur soit vraiment rangé ? Genre quand il le rouvrira lui même, il apparaîtra de nouveau tel qu'il l'aura rangé ?

**Comment by Maskowh** [comment]
Oui c'est l'idée. Dans l'idée ce sera une copie de l'inventaire du joueur fouillé qui sera affichée, et la correspondance sera faite avec un mapping entre la position dans la copie et la position réelle.

**Comment by NariieL** [comment]
Hello! We don't want this change. Thank you for suggesting this. <3
