### ISSUE TITLE
[NG] Ajouter les autres types de pneus

### ISSUE THREAD

**Issue by Mcfloy** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

New Gahray

### Explain the current situation that you do not think is right.

Actuellement il manque certaines catégories de pneus dans les options de New Gahray alors que RP parlant il n'y a aucune raison de resteindre ces choix (ce sont des modifications purement visuelles)

### How is the improvement you propose?

Ajouter les différents types dans le menu.

**Comment by poulpito** [comment]
Pour information au cas ou j'ai repris dans la #245 vu que c'est un amélio globale NG   
En limitant les openwheel pour les voitures type openwheel. (sinon ca fait des dingueries)

**Comment by NariieL** [comment]
Accepted! But we'll take Poulpito's PR, which is more complete. Thanks to you for suggesting this improvement. <3
