### ISSUE TITLE
[Issue] GetPlayIdentifierByType

### ISSUE THREAD

**Issue by ghost** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#224]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of Issue

Après avoir fait l'installation du serveur en ayant suivi toutes les instructions, nous nous connectons, et nous avons cette erreur qui apparait plusieurs fois dans la console, et pour chaque joueur.

Également, mais sans erreur visible dans la console, lors de la première connexion d'un personnage, le nom du personnage Five M n'est pas pris en compte dans les papiers nous laissant tous être appelé en jeu ou via les papiers (Santé, Permis, Carte d'identité) " First Name - Last Name ".

```console
[     script:soz-core] Error: Unhandled promise failure: ReferenceError: GetPlayerIdentifierByType is not defined
[     script:soz-core]     at Jo.getPlayerIdentifierByType (@soz-core/build/server.js:2:1308790)
[     script:soz-core]     at Jo.getIdentifier (@soz-core/build/server.js:2:1309042)
[     script:soz-core]     at Ls.getJwtToken (@soz-core/build/server.js:2:1345500)
[     script:soz-core]     at a (@soz-core/build/server.js:2:1121417)
[     script:soz-core]     at @soz-core/build/server.js:2:1142191
[     script:soz-core]     at @soz-core/build/server.js:2:1143643
[     script:soz-core]     at @soz-core/build/server.js:2:1143072
[     script:soz-core]     at @soz-core/build/server.js:2:1142806
[     script:soz-core]     at citizen:/scripting/v8/main.js:477:30
[     script:soz-core]     at Number.__cfx_wrap_1021 (citizen:/scripting/v8/main.js:23:12)
[      script:oxmysql] [WARNING] qb-core triggered a deprecated function! Exports from prior to v1.9.0 will be removed in a future update.
[      script:oxmysql]       Refer to the readme for information on updating.
[     script:soz-core] Error: Unhandled promise failure: ReferenceError: GetPlayerIdentifierByType is not defined
[     script:soz-core]     at Jo.getPlayerIdentifierByType (@soz-core/build/server.js:2:1308790)
[     script:soz-core]     at Jo.getIdentifier (@soz-core/build/server.js:2:1309042)
[     script:soz-core]     at Ls.getJwtToken (@soz-core/build/server.js:2:1345500)
[     script:soz-core]     at a (@soz-core/build/server.js:2:1121417)
[     script:soz-core]     at @soz-core/build/server.js:2:1142191
[     script:soz-core]     at @soz-core/build/server.js:2:1143643
[     script:soz-core]     at @soz-core/build/server.js:2:1143072
[     script:soz-core]     at @soz-core/build/server.js:2:1142806
[     script:soz-core]     at citizen:/scripting/v8/main.js:477:30
[     script:soz-core]     at Number.__cfx_wrap_1099 (citizen:/scripting/v8/main.js:23:12)
[     script:soz-core] Error: Unhandled promise failure: ReferenceError: GetPlayerIdentifierByType is not defined
[     script:soz-core]     at Jo.getPlayerIdentifierByType (@soz-core/build/server.js:2:1308790)
[     script:soz-core]     at Jo.getIdentifier (@soz-core/build/server.js:2:1309042)
[     script:soz-core]     at Ls.getJwtToken (@soz-core/build/server.js:2:1345500)
[     script:soz-core]     at a (@soz-core/build/server.js:2:1121417)
[     script:soz-core]     at @soz-core/build/server.js:2:1142191
[     script:soz-core]     at @soz-core/build/server.js:2:1143643
[     script:soz-core]     at @soz-core/build/server.js:2:1143072
[     script:soz-core]     at @soz-core/build/server.js:2:1142806
[     script:soz-core]     at citizen:/scripting/v8/main.js:477:30
[     script:soz-core]     at Number.__cfx_wrap_1224 (citizen:/scripting/v8/main.js:23:12)
[     script:soz-core] Error: Unhandled promise failure: ReferenceError: GetPlayerIdentifierByType is not defined
[     script:soz-core]     at Jo.getPlayerIdentifierByType (@soz-core/build/server.js:2:1308790)
[     script:soz-core]     at Jo.getIdentifier (@soz-core/build/server.js:2:1309042)
[     script:soz-core]     at Ls.getJwtToken (@soz-core/build/server.js:2:1345500)
[     script:soz-core]     at a (@soz-core/build/server.js:2:1121417)
[     script:soz-core]     at @soz-core/build/server.js:2:1142191
[     script:soz-core]     at @soz-core/build/server.js:2:1143643
[     script:soz-core]     at @soz-core/build/server.js:2:1143072
[     script:soz-core]     at @soz-core/build/server.js:2:1142806
[     script:soz-core]     at citizen:/scripting/v8/main.js:477:30
[     script:soz-core]     at Number.__cfx_wrap_3579 (citizen:/scripting/v8/main.js:23:12)
[     script:soz-core] Error: Unhandled promise failure: ReferenceError: GetPlayerIdentifierByType is not defined
[     script:soz-core]     at Jo.getPlayerIdentifierByType (@soz-core/build/server.js:2:1308790)
[     script:soz-core]     at Jo.getIdentifier (@soz-core/build/server.js:2:1309042)
[     script:soz-core]     at Ls.getJwtToken (@soz-core/build/server.js:2:1345500)
[     script:soz-core]     at a (@soz-core/build/server.js:2:1121417)
[     script:soz-core]     at @soz-core/build/server.js:2:1142191
[     script:soz-core]     at @soz-core/build/server.js:2:1143643
[     script:soz-core]     at @soz-core/build/server.js:2:1143072
[     script:soz-core]     at @soz-core/build/server.js:2:1142806
[     script:soz-core]     at citizen:/scripting/v8/main.js:477:30
[     script:soz-core]     at Number.__cfx_wrap_3671 (citizen:/scripting/v8/main.js:23:12)
[     script:soz-core] Error: Unhandled promise failure: ReferenceError: GetPlayerIdentifierByType is not defined
[     script:soz-core]     at Jo.getPlayerIdentifierByType (@soz-core/build/server.js:2:1308790)
[     script:soz-core]     at Jo.getIdentifier (@soz-core/build/server.js:2:1309042)
[     script:soz-core]     at Ls.getJwtToken (@soz-core/build/server.js:2:1345500)
[     script:soz-core]     at a (@soz-core/build/server.js:2:1121417)
[     script:soz-core]     at @soz-core/build/server.js:2:1142191
[     script:soz-core]     at @soz-core/build/server.js:2:1143643
[     script:soz-core]     at @soz-core/build/server.js:2:1143072
[     script:soz-core]     at @soz-core/build/server.js:2:1142806
[     script:soz-core]     at citizen:/scripting/v8/main.js:477:30
[     script:soz-core]     at Number.__cfx_wrap_3777 (citizen:/scripting/v8/main.js:23:12)```

### Expected Behavior

N/A

### Reproduction Steps

- Installer le serveur comme indiquer dans la partie " tutoriel ".
- Installer proprement un serveur Five M " Vanilla "
- Lancer le serveur
- Lancer Steam, puis Five M et se connecter au serveur
- Regarder les erreurs dans la console

### Does it happen all the time ?

Cela survient à chaque connexion d'un joueur sur le serveur après son lancement systématiquement.
- Hébergement sous Windows 11 64 Bits v.22621.1848
- AMD Ryzen 7 3700X | 32 GB RAM DDR4 | RTX 3060 TI Gaming Z Trio 8G
- Node v18.16.1
- MariaDB v11.0 (HeidiSQL v.12.3.0.6589)
- Yarn v1.22.19

**Comment by Laikker** [comment]
Salut,

Pour le GetPlayerIdentifierByType je soupçonne que tu utilises un niveau artefact trop ancien, tu peux essayer de mettre à jour ton FiveM? Après comme tu n'as pas le serveur du panel, tu auras forcemenent des erreurs.
Pour le " First Name - Last Name ", normalement on utilise les données issue du panel lors de la création du person en jeu, tu  peux regarder resources/[qb]/qb-core/server/functions.lua: QBCore.Functions.GetUserAccount

**Comment by ghost** [comment]
Hello @Laikker !

Merci, concernant l'artefact de FiveM en effet c'était bien le problème, concernant le " First Name - Last Name ", j'avais bien trouver le functions.lua, et effectuer la modification pour ajouter les données qu'il faut dans notre SQL, mais quand tu parles du panel en jeu, on n'a aucune option pour définir un nom/prénom de personnage quand on rejoins le serveur de notre côté. Tu parles bien du menu de création avec les habits, les traits du visage etc... ?

Cordialement

**Comment by Laikker** [comment]
Sur Soz, le prenom et nom sont démandés et sauvegarder lors de l'enregistrement sur le site web. Lors de la creation du perso in game (habits, traits du visage), ces info sont récupéré depuis la DB du site web et poussé dans la DB jeu. A vous de voir comment vous voulez le gérer pour votre serveur

**Comment by ghost** [comment]
Hello @Laikker !

Ah je comprends mieux, car j'ai bien un champ " name " dans ma SQL qui est rempli par FiveM lors de la création du personnage, mais c'est uniquement dans charinfo que le problème est. Je vais essayer de voir avec un développeur qui puisse prendre en compte la valeur de " Name ".

Merci beaucoup !

**Comment by ghost** [comment]
J'ai un petit problème avec la barre de santé (sauf si des dégâts sont pris ou qu'on se trouve dans un véhicule), de soif et de nourriture, celle-ci n'apparait jamais, même après plusieurs heures de jeu et dans n'importe quelle situation.

Je n'ai aucune erreur dans la console concernant cela. S'agit-il d'une feature voulue ? Si oui, quels sont les fichiers gérants cela ?

**Comment by dave-creach** [comment]
Bonjour, 
Pour la barre de vie elle apparait que lorsqu'elle est nécessaire quand le joueur n'est pas dans un véhicule (en dessous de 60%). Le fichier qui gère ça et celui là : https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/blob/995232da952952e78280711de619271054247ced/resources/%5Bsoz%5D/soz-core/src/nui/components/Hud/Minimap.tsx#L20 

Pour de la barre de faim et soif, j'ai une question pour toi. Est-tu en mode "god mode" du menu admin car si oui c'est normal la barre de faim et de soif ne descend pas. D'autres pars la barre de faim et de soif n'apparait que lorsque nécessaire comme celle de vie.

**Comment by ghost** [comment]
Hello @dave-creach,

Merci beaucoup pour ces détails, la personne concernée doit être en god mod je pense oui, ce qui est du coup beaucoup plus censé. Tu aurais par hasard le fichier qui gère cela ?

Cordialement.

**Comment by dave-creach** [comment]
Hello, 

Je pense que c'est ce fichier qui gère cela. Tu peux fouiller pour regarder dans le détail comment c'est gérer.
https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/blob/995232da952952e78280711de619271054247ced/resources/%5Bsoz%5D/soz-admin/server/module/gamemaster.lua#L36

**Comment by ghost** [comment]
Hello,

Merci de ton retour, c'est parfait ! :)
