### ISSUE TITLE
[Phone] Snake

### ISSUE THREAD

**Issue by Maskowh** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Ajout d'un Snake dans les applis du téléphone

### Explain all the steps and mechanics clearly and precisely.

Ajout d'un Snake dans les applis du téléphone, avec sauvegarde du meilleur score en base de données.

### Why would this feature be useful?

C'est toujours sympa un p'tit Snake au milieu d'une réunion RP non?

**Comment by Maskowh** [comment]
Petit aperçu. Il me reste la sauvegarde en base à faire et quelques retouches graphiques

https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/assets/123783610/77eafcdc-bd4f-47a2-b03d-2dd58b775700

**Comment by Maskowh** [comment]
C'est fini, j'ai fait la PR.

Au niveau code, j'ai encore un peu de mal avec la gestion des events donc j'ai peur d'avoir fait quelque chose de trop complexe pour rien

Au niveau graphique, c'est pas un métier fait pour moi, donc l'icone de l'App et l'aplication en elle-même ne sont, visiblement, pas faites par un graphiste.
Si c'est trop horrible je peux demander sur le discord si quelqu'un a une meilleure proposition

**Comment by NariieL** [comment]
Accepted. You have the freedom to develop this, thank you. <3

**BUT! Pay attention to the aesthetics of your game. Currently, we'll refuse the PR if it's in this state.**

You can take inspiration from mobile games, by creating a more simplistic UI.

> ![image](https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/assets/104008465/721e1433-39f9-4038-a6ed-e6b8bb1c279b)

**Comment by Maskowh** [comment]
Bonjour @NariieL , j'ai récupéré le classement et les boutons du Tetris, et Magog m'a proposé des sprites pour le serpent, le fruit et le mur. Est-ce que ça te convient?

https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/assets/123783610/60b746a2-8397-4a14-9bea-12107c84f5ee

**Comment by NariieL** [comment]
Retire le rectangle du score, et augmente la taille du score en y ajoutant un petit effet arcade.

**Comment by NariieL** [comment]
Le fond utilisé est bien en .webp en bon format pour économiser le poids ?

**Comment by NariieL** [comment]
Tu peux aussi augmenter la surface de jeu, un rectangle s'mieux qu'un carré.

**Comment by NariieL** [comment]
Pour le score, tu peux faire :

Icone tête de serpent + chiffre taille 
Icone Score + Score

L'un à côté de l'autre, bien proprement

**Comment by Maskowh** [comment]
![image](https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/assets/123783610/a7a8e67d-2525-4145-8d64-fdab19e0a65f)

Bonsoir @NariieL , est ce que cela te convient mieux? Pas de tête de serpent pour la taille, j'aimais pas trop le rendu. le reste a été pris en compte.

**Comment by NariieL** [comment]
Validé. T'as géré Maskowh. Merci à toi.

**Comment by Maskowh** [comment]
Merci. La PR est à jour. 

Si c'est accepté en prod, est-ce qu'il sera possible de créditer Magog dans la note de patch? Il a fait les sprites du serpent, du fruit et des murs. Merci!

**Comment by Laikker** [comment]
Merci pour la proposition qui a été intégré au serveur
