### ISSUE TITLE
[Animation] Ajout d'une animation pour que tous le monde puisse utiliser l'animation de s'asseoir comme les hommes

### ISSUE THREAD

**Issue by MimiBloops** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

Animation

### Explain the current situation that you do not think is right.

L'animation par défaut de s'asseoir au sol des hommes n'est pas accessible aux femmes. Pour les perso pas très féminin l'animation de s'asseoir au sol n'est pas super adaptée.

### How is the improvement you propose?

Ajouter pour tous le monde l'animation pour s'asseoir au sol des hommes.

**Comment by MimiBloops** [comment]
P'tite preview : 
https://youtu.be/QQQyx4yhfDg

**Comment by MimiBloops** [comment]
Je viens de me rendre compte que le clip n'est pas bon... Il s'agit simplement de l'animation de s'asseoir par défaut des hommes mais disponible également pour les femmes.
Nouveau Clip : https://youtu.be/lY_tEul2WEc

**Comment by NariieL** [comment]
Accepted. We'll be taking a closer look very soon. <3

**Comment by Laikker** [comment]
Thanks for the proposition, the possiblity has been added
