### ISSUE TITLE
Notes partagées

### ISSUE THREAD

**Issue by Maskowh** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

L'idée est de permettre des notes partagées.

### Explain all the steps and mechanics clearly and precisely.

L'idée est donc d'enrichir l'application Notes et de permettre de créer des "Notes partagées".
En plus du fonctionnement standard des notes, elles disposeraient d'un bouton permettant de les partager à des contacts.
Ces contacts verraient alors les notes ainsi partagées apparaître dans leur appli en read-only.
Couplée à #222  je pense que cela permettra de gérer des minis compta de groupes, d'assos, grâce aux tableaux, de partager des infos (récap pour ceux qui n'étaient pas là), ...

### Why would this feature be useful?

Dans mon groupe, on essaie de jouer sans GDoc, mais c'est parfois compliqué de faire transiter les infos.

La feature permettrait d'avoir une alternative à l'utilisation d'outils externe style gsheet/gdoc, et j'ai essayé que la proposition soit assez équilibrée (on est pas sur de l'édition simultanée comme un vrai gdoc pour éviter la complexité de la mise à jour simultanée)

**Comment by NariieL** [comment]
This PR is rejected! <3 We don't want that. It's better to simply see each other - dialogue to share information rather than write it down.
