### ISSUE TITLE
[Demande SOZ] [Feature] SOZ Hammer

### ISSUE THREAD

**Issue by Zocaxu** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#237]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Proposition d'un nouveau mode Editeur permettant la création et la gestion de props synchronisés.

### Explain all the steps and mechanics clearly and precisely.

# SOZ Hammer : Placement de props et création d'événements

SOZ Hammer permet à n'importe quel joueur autorisé de placer des props et de créer des scènes/évènements personnalisés directement en jeu.

## Objectifs principaux

- Offrir la possibilité de placer et faire apparaître des props 3D, de manière immédiate et synchronisée entre les joueurs.
- Fournir un éditeur pratique intégré au jeu, permettant au joueur de placer son prop via un Gizmo intuitif.
- Permettre la création d'événements regroupant plusieurs props, facile et rapide à pré-créer, faire apparaitre, faire disparaître et supprimer.

### Le Marteau

- [x] Permettre aux admins/staffs d'autoriser à volonté n'importe quel joueur à accéder à SOZ Hammer. 
- [x] Utilisation du Hammer via un objet unique "Marteau" présent dans l'inventaire du joueur autorisé.
- [x] Cet objet n'est ni achetable, ni échangeable, ni stockable. 

### Placement de prop

- [x] Fournir une interface pratique à utiliser permettant de déplacer et tourner le prop à placer.
- [x] Associer un Gizmo au prop à placer, permettant au joueur de placer le prop facilement à la souris.
- [x] Avoir un "Snap mode" pour que le prop à placer se place automatiquement sur le sol.

### Liste de props

- [x] Fournir une liste prédéfinie de 1600 props (modèles 3D) pouvant être placés par le joueur, regroupés en 41 catégories.
- [x] Autoriser le joueur à rentrer manuellement le modèle qu'il souhaite placer, même s'il n'est pas dans la liste des props prédéfinies. *Attention aux abus...*

### Création d'événements

- [x] Permettre la création d'événements à travers les "**collections**".
- Une **collection** est un ensemble de props. Une collection possède un nom, un créateur, une date de création et une liste de props placés dans le monde et associés à cette collection
- [x] Permettre la création d'un événement "à l'avance". Le créateur peut placer ses props à l'avance sans que les autres joueurs ne les voient.
- [x] Permettre au joueur de faire apparaître (on dit que la collection est alors *chargée*) et disparaître (respectivement, *déchargée*) une collection créée à l'avance pour tous les autres joueurs en un seul bouton.
- [x] Permettre au joueur d'éditer sa collection (déplacer, ajouter, supprimer des props) à son bon vouloir, même lorsque sa collection est chargée. Cela offre une liberté totale de création et édition.
- [x] Lors d'un ouragan, toutes les collections disparaissent du monde (elle sont toute déchargées). Mais rien n'empêche le créateur de recharger sa collection après l'ouragan ! (Les événements de sont pas destinés à durer plusieurs jours pour le moment.)

### Collections privées

- [x] Permettre uniquement au créateur d'une collection de la voir et de la modifier via SOZ Hammer. Tous les joueurs peuvent voir les props dans le monde quand la collection est chargée, mais seul le créateur peut modifier ces props.

### Charge serveur et charge client

- [x] SOZ Hammer affiche la **charge du serveur** : le nombre total de props synchronisés sur SOZ. Cette charge augmente à mesure que les créateurs chargent leurs collections. Cette charge retombe à **0** lors d'un ouragan.
- [x] SOZ Hammer affiche la **charge du client** : le nombre total de props affichés pour le joueur. Cette charge **doit être égale aux nombres de props synchronisés**.
- [x] SOZ Hammer fournit un système de resynchronisation si une désynchronisation par rapport au serveur est constatée. 

### Idées futures

- Création en coopération : le créateur peut donner les droits à un autre joueur pour créer ensemble un évènement
- Housing : permettre la personnalisation de son appartement via SOZ Hammer. Le fonctionnement serait alors probablement différents : les props d'un appartement ne sont affichés que pour les joueurs qui sont à l'intérieur, afin de limiter la charge du client.
- Associer SOZ Hammer au Zkea, où les joueurs peuvent acheter les props à placer.

### Why would this feature be useful?

Proposer une liberté totale et création pour tous les joueurs à terme. SOZ devient un vrai bac à sable !

**Comment by NariieL** [comment]
C'est mergé! Merci à toi pour la contribution <3
