### ISSUE TITLE
[CJR] LE bus de CJR aux couleurs de CJR ! 

### ISSUE THREAD

**Issue by Astreyol** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

BUS - CJR

### Explain the current situation that you do not think is right.

le bus carl junior est avec un skin de base on aimerai un bus custo CJR

### How is the improvement you propose?

on propose de mettre le bus de CJR au couleurs de CJR

**Comment by NariieL** [comment]
Accepted. We'll be taking a closer look very soon. <3

**Comment by Laikker** [comment]
Thanks for the proposition, it has been intégrated
