### ISSUE TITLE
[Phone]Musique Streaming Application aka Zpotify

### ISSUE THREAD

**Issue by terrainwax** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Ajout d'une app type spotify pour écouter la musique produite en RP par les joueurs

### Explain all the steps and mechanics clearly and precisely.

https://docs.google.com/document/d/1_xmOtHDLYGvTdDqzd0ZlPSIAxcATHCh3bBEfaxDgFPE/edit?usp=sharing

### Why would this feature be useful?

Cette ajouts permet d'ajouter du RP au personne qui s'investisse musicalement pour SOZ et ajouter une sorte de mémoire collective vis à vis des chanson qui peuvent avoir une histoire en plus de permettre au gens d'écouter ces chanson de plus je prévois d'ajouter la possibilité de mettre sur haut parleur  ou de ce connecter en Bluetooth a des enceintes et donc de partager la musique a tout le monde qui se trouve au alentour de la source audio

**Comment by terrainwax** [comment]
![image](https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/assets/14014510/0df8de19-a553-4326-a31d-9a1eb7aa0808)

**Comment by NariieL** [comment]
Ola ! Quelle utilité l'application peut avoir par rapport aux pochettes d'Album qui existe déjà ? Cela fait double Feature pour exactement la même chose, non ?

**Comment by terrainwax** [comment]
Le but c'est surtout de créer du RP aujourd'hui les pochettes comme expliqué sont a implémenter dans le code la ou l'appli serait complètement géré via des packet client server et comme expliqué dans le GDD on pourrait imaginer que la version gratuite aurais des pub créé par TN et que les revenus des abonnements et d'une partie des pub soit reversée aux artiste en fonction de leurs nombre de stream mais effectivement il faudrait trouver une utilité aux albums déjà existant (peut-être des objets collectors)

**Comment by terrainwax** [comment]
Après l'application a aussi été construit de sorte a préparer le bluetooth pour diffuser a tout le monde la musique en synchro

**Comment by terrainwax** [comment]
J'ai revue un peu mon "jugement" je pense que ça sera  plus une upgrade du systems d'album actuel avec une belle UI les album resteront il perdront sûrement leurs bouton utiliser dans l'inventaire mais en gros si tu as l'album dans ton inventaire il et débloquer dans Zpotify je pense c'est un bon compromis je suis entrain de voir aussi pour pouvoir ajouter des items "a la voler" sans faire de mise à jours et donc pouvoir faire des sortie d'album sans MAJ

**Comment by NariieL** [comment]
Accepted. You have the liberty of developing this, thank you. <3

**But there are a few things to bear in mind:**
- Your application must be linked to the albums. This means that if an album is added to the shop, it's must be available for listening in the app.
- You can define a custom Album image for the application, but it must be simple to add.

This will give you two ways of supporting the artist, either by buying the album, or by listening to it on the app.
