### ISSUE TITLE
[Weapon Draw] Allow user to play switchblade animation. 

### ISSUE THREAD

**Issue by poulpito** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

Weapon system and function to draw / undraw.

### Explain the current situation that you do not think is right.

Currently the switchblade is draw from the back  like any other hidden weapon. 
it's not possible to play the switchblade animation and the sound effect. 

### How is the improvement you propose?

I've modify the draw / undraw function to handle the switchblade and slightly modify the animation to include sound effect that was not present. 
weapon handling for quicker draw when job police  is not modified. 

PR is ready to be pushed. 
( https://github.com/poulpito/SOZ-FiveM-Server/tree/feat/Switchblade ) 

Vidéo preview : 

https://youtu.be/QLqxxJR57h8
https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/assets/4135866/c0d5aeb6-8acf-4210-bf14-e971590d78ba

**Comment by NariieL** [comment]
Accepted. You have the liberty of developing this, thank you. <3

**Comment by Laikker** [comment]
Thanks for the proposition, it has been implemented from the PR
