### ISSUE TITLE
[NG/Vehicle] Add support for HSW Cameleon Pain & missing tires type. 

### ISSUE THREAD

**Issue by poulpito** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

New Gahray / Vehicle 

### Explain the current situation that you do not think is right.

MIssing cameleon paint  and multiple rim/tires missing. 

### How is the improvement you propose?

List of modifications 
- HSW Files (carcols/cargen/ytd) have been add into a soz-hswpaint ressource in [vehicles]  
- Camelon paint is available for Primary / Secondary and all other color option like pearlescent and rim color 
(82 new paint variation)
- 3 new rim/tire categories for normal cars (Bespoke / Street / Track) 
- Openwheel category with dedicated rim/tire choice if someday we want to custom it.  (openwheel tire restricted to only openwheel)

Video Preview of NG menu (same for admin menu)  is available below 
https://www.youtube.com/watch?v=8uQyqqWQxYQ

Code is ready to be PR 
[ https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/compare/oss...poulpito:SOZ-FiveM-Server:feature/NG-addon ]

**Comment by NariieL** [comment]
Accepted. You have the liberty of developing this, thank you. <3

**Comment by Laikker** [comment]
Merci pour la proposition qui a été intégré au serveur
