### ISSUE TITLE
[Tattoo Shop] Move camera position & add front/back category 

### ISSUE THREAD

**Issue by poulpito** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#252]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

Tattoo Shop

### Explain the current situation that you do not think is right.

Cannot see properly a hand tatoo due to camera position
Difficult to jump between camera for all torso tattoo

### How is the improvement you propose?

- Camera position for arm left/right have been moved away and lower so a full view is possible
![FiveM_b2944_GTAProcess_kwg9WCyi3y](https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/assets/4135866/bf9e7554-e91a-4c63-87a8-9e80b2d68b9a)

- Divide Torso cat into Front / Back  with multiple camera angle 
![FiveM_b2944_GTAProcess_ARxOL0Rwmd](https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/assets/4135866/1ba8f1a1-e69a-4699-b214-135f2bf980d7)

- Add description in menu  to use Shift Key to swap between camera (just in case ... many players doesn't know it and avoid lower right notification) 
![FiveM_b2944_GTAProcess_7V7z5JgyOw](https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/assets/4135866/444e8278-e45d-485f-849c-34d1201a442c)

**Comment by NariieL** [comment]
Accepted!

**Comment by Laikker** [comment]
Merci pour cette divine proposition qui a été intégré au serveur
