### ISSUE TITLE
[SOZ-Phone] Ajout de l'adresse dans l'affichage d'un message de "Destination"

### ISSUE THREAD

**Issue by f0wlerz** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

Modification de l'affichage des messages de position

### Explain the current situation that you do not think is right.

Actuellement les messages contenant une position montrent uniquement le message "Destination" à côté de l'icône de Blip.

### How is the improvement you propose?

J'aimerais mettre en place l'affichage de l'adresse la plus proche du blip / vecteur comme si la personne envoyait textuellement son adresse ou un lien vers celle-ci qui l'afficherait. Cela ressemblerait à cela par exemple.
![image](https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/assets/144132140/1e5e623a-625e-41a5-8291-fa88f7adff6b)

**Comment by NariieL** [comment]
Accepted! Waiting for your PR. <3

**Comment by Laikker** [comment]
Integrated
