### ISSUE TITLE
[LSMC] Gestion de la licence de secourisme

### ISSUE THREAD

**Issue by Kedrihan** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

LSMC

### Explain the current situation that you do not think is right.

Actuellement, la licence de secourisme ne sert à rien car aucun job ne peut la donner, alors que en RP le LSMC fait des formations aux premiers secours. Ce qui les oblige à noter de leur côté en dehors du jeu la liste des personnes aptes à réaliser les premiers secours.

### How is the improvement you propose?

Je propose donc que les médecins du LSMC puissent décerner ou retirer la licence de secourisme aux joueurs par le BTarget, à l'image du PPA pour les FDO.
Sur une idée d'UnclePeps, je propose aussi de limiter l'utilisation de défibrillateur et de l'animation de massage cardiaque aux personnes ayant la licence de secourisme uniquement.

**Comment by NariieL** [comment]
Hello! This will be done at the same time as the LSMC overhaul. <3 Thanks anyway.
