### ISSUE TITLE
[Barber shop] "Densité" ne fonctionne pas.

### ISSUE THREAD

**Issue by Alithegood** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#27]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of Issue

Impossibilité d'appliquer du rouge a lèvre
Comment se produit-il : Lors de la modification du personnage chez le coiffeur, même si l'on change l'intensité du rouge a lèvre a plusieurs reprises et après validation aucune couleur visible (on reste avec le rouge a lèvres appliqué le jour de notre arrivé sur le serveur)

Le fait aussi pour tout ce qui a de la densité

### Expected Behavior

Changer la densité dans le baber shop modifie la densité sur le personnage

### Reproduction Steps

Aller dans un baber shop modifier et payer.

### Does it happen all the time ?

oui

**Comment by NariieL** [comment]
Thanks for your contribution. <3 Merge in https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/commit/b0d4032d91603c1e22280e3d6704ff916d3edbc0
