### ISSUE TITLE
[FFS] [Wardrobe] Gestion des vestiaires des entreprises privées en jeu par FFS

### ISSUE THREAD

**Issue by f0wlerz** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Ceci est une reprise de #132 (vue avec Maskowh) dont le but est de permettre la **modification** des tenues des vestiaires en jeu directement par FFS. L'idée est qu'avec une permission spéciale de l'entreprise FFS, des employés puissent **ajouter**, **renommer** et **supprimer** les tenues des vestiaires des **entreprises privées** de la même manière que les joueurs gèrent leur dressing personnel.

### Explain all the steps and mechanics clearly and precisely.

La mécanique se présente ainsi : 
- Les employés de FFS qui ont la permission de modifier les vestiaires entreprises ont un B-Target de plus sur les vestiaires des entreprises privées.
- Ce B-Target leur ouvre un menu en jeu semblable à celui des dressings personnels qui offre les possibilités suivantes :
    -> Ajouter une tenue (celle que le joueur de FFS porte)
    -> Renommer une tenue déjà existante
    -> Supprimer une tenue déjà existante.
**N.B. :** La gestion des tenues est donc séparée entre personnages masculins & féminins afin de ne pas créer de conflit / de soucis avec les vêtements (les personnages travaillant à FFS de sexe masculin n'auront accès qu'aux tenues pour homme du vestiaire considéré et réciproquement).

Comme NariieL l'avait demandé dans l'issue originelle de Maskowh, il faut une restriction afin les joueurs ne changent pas les tenues tous les 3 jours ou qu'ils en fassent un nombre trop important de différentes. Deux choses sont mises en place pour cela :
- Pour ajouter une tenue au vestiaire, il faut un item (à définir, tel qu'un Cintre ou une Housse de vêtement) qui est consommé lors de l'ajout. Cet item doit être acheté ou crafté par FFS, ce qui permet de fixer un prix assez élevé d'emblée afin de limiter les changements trop fréquents.
- Une limite de tenues peut également être imposée. (ex : pas plus de 10 tenues - donc 5 par sexe- par entreprise). Là encore, cela permet notamment de mettre en place une limite facile sur la collectionite des tenues. Ca laisse également la porte ouverte à une amélioration de vestiaire dans le futur si on veut rendre cette limitation dynamique en fonction des entreprises et de si elles paient pour augmenter le plafond maximal.

**N.B. :** D'un point de vue technique, il faut noter que pour que cela fonctionne les vestiaires entreprises doivent dorénavant être hébergés dans la base de données.

### Why would this feature be useful?

Cette feature peut être utile pour deux raisons majeures : 
- Permettre une interaction supplémentaire à FFS dans leur rôle de personnal (et donc maintenant professionnal) shopper.
- Soulager le travail des devs / staffs qui doivent faire les modifications à la main dans les job cloakrooms.

**Comment by TheAzylium** [comment]
Pour le problème des différents sexes, pourquoi ne pas relier la tenue aux métadonnées du cintre ? Je m'explique :

Une entreprise fait une demande à FFS pour une tenue supplémentaire pour femme. Un rendez-vous est alors fixé dans un lieu prévu à cet effet (local spécial chez FFS où toutes les tenues sont disponibles). Sur place, un mannequin du sexe souhaité pourrait apparaître, et la prévisualisation de la tenue se ferait sur ce mannequin. Une fois la tenue validée, celle-ci serait sauvegardée sur le cintre. Ainsi, un homme ou une femme pourrait ensuite ajouter une tenue pour le sexe opposé. Cela éviterait également de voir un homme de FFS se balader en tenue du LSPD SWAT pour ajouter une tenue.

**Comment by f0wlerz** [comment]
L'idée du studio peut être vraiment intéressante et serait dans ce cas à lier avec la showroom de #73 (dans lequel on pourrait probablement mettre un mannequin). A voir si le staff accepte de laisser FFS accéder à tous les vêtements y compris les moddés / hors shops (si c'est déjà le cas je ne suis pas au courant j'avoue).

**Comment by NariieL** [comment]
A very good idea, but for the moment, we prefer to control the outfits modified and added to companies. Maybe later! <3 Thanks.
