### ISSUE TITLE
[Vehicule] Mieux déterminer la portière lors de l'entrée dans un véhicule

### ISSUE THREAD

**Issue by Zocaxu** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

Véhicule, portes

### Explain the current situation that you do not think is right.

Lors de l'entrée dans un véhicule (particulièrement les voitures avec 4 portes), la porte dans laquelle rentre le ped est parfois peu intuitive, et il est nécessaire de s'approcher du pneu du véhicule pour rentrer devant par exemple.

### How is the improvement you propose?

Cette amélioration utilise une native FiveM ```GetEntryPositionOfDoor``` afin de mieux déterminer la portière que le ped doit ouvrir.
Globalement, cette native améliore considérablement la manière dont le ped entre dans un véhicule, en rendant la mécanique plus intuitive (le ped rentre dans la portière dont la poignée est la plus proche, et non la charnière).

*Disclaimer : une précédente tentative avait été effectuée afin de pallier au même problème. La précédente tentative utilisait le bone des poignées des portes, ce qui pouvait conduire à des bugs sur certains véhicules. Le fonctionnement proposé ici est complètement différent et utilise une nouvelle native propre, plus robuste.*

Le code proposé à été testé sur :
- Les voitures 2 portes
- Les voitures 4 portes
- Les motos
- Les bateaux
- Les hélicoptères
- Les bus

Toutes les classes de véhicules fonctionnent très bien avec cette native et cette nouvelle mécanique

*Note : Un bug connu existe sur certains vans avec le fonctionnement actuel et le nouveau proposé dans cette issue, et qui cause le ped à rentrer en priorité dans la siège conducteur. Le bug semble lié à FiveM et je n'ai malheureusement pas pu le corriger pour le moment.*

**Comment by Zocaxu** [comment]
https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/assets/72206163/2eef0ba2-d7cc-4e8b-89aa-38feec236b41

**Comment by poulpito** [comment]
\o 
La gestion des bones avaient été introduite pour palier aux soucis de la native pour les véhicules spé
(6 places , camion poubelle, pompier, neon qui a les bones assez proche) 

et aussi le comportement une fois la porte arrachée (ou des fois tu peux plus monter dedans) 
- si porte arrachée je prenai le bone du siège - 
Si tu as de quoi tester :)

**Comment by Zocaxu** [comment]
OK !
Plus de tests vont être conduits sur les véhicules spés, et dans les cas où les portes sont pétées.
Update soon !

**Comment by Laikker** [comment]
Merci pour la PR, ça fait plus d'un an que ça a été intégré sur le serveur sans souci
