### ISSUE TITLE
[SOZ-Jobs] Tableau d'informations

### ISSUE THREAD

**Issue by f0wlerz** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#278]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

L'essentiel de la feature consiste en un ajout d'un Prop type [prop_cork_board](https://forge.plebmasters.de/objects/prop_cork_board?search=cork_board) dans les locaux de chaque entreprise s'il n'existe pas. Ainsi, les employés de l'entreprise ayant la permission de le faire pourront créer des entrées sur ce tableau consultable **en jeu** par tous et qui agirait l'équivalent d'un canal annonces d'un discord d'entreprise.

### Explain all the steps and mechanics clearly and precisely.

- Présence d'un prop [prop_cork_board](https://forge.plebmasters.de/objects/prop_cork_board?search=cork_board) dans chaque local d'entreprise privée / service public.
- Prop B-targetable avec deux options : 
     - Consulter le tableau de service (qui ouvre la liste des entrées épinglées sur le tableau) - disponible pour tous
     - Gérer le tableau de service (ajouter, modifier et retirer des entrées) - disponible aux personnes qui ont la permission associée

On peut également réfléchir à la modification du tableau en passant par le panel entreprise avec un onglet spécial mais à discuter avec les dev web de SOZ.

### Why would this feature be useful?

Cette feature permettrait de réduire le rôle prépondérant de Discord dans les interactions entreprise en décalant certains canaux / la disponibilité des informations vers le jeu.

**Comment by NariieL** [comment]
Accepté !

**Comment by f0wlerz** [comment]
Dropped project
