### ISSUE TITLE
[Core] Bloqué l'alimentation si Casque ou Masque bloque l'accès à la bouche

### ISSUE THREAD

**Issue by TheAzylium** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Je suggère de bloqué l'utilisation de l'alimentation si on possède un masque ou un casque qui bloque l'accès à la bouche.

### Explain all the steps and mechanics clearly and precisely.

Lorsque l'on tente de manger ou boire si notre masque ou notre casque bloque notre bouche alors cela annule l'action et préviens le joueur du pourquoi du comment il ne peux pas manger.

### Why would this feature be useful?

Cette feature ajouteras une difficulté supplémentaire lors de prise d'otage, ou simplement d'une conduite moto car pour manger ou boire les gens vont devoir s'exposer

**Comment by MrKoddy** [comment]
Pour l'avoir expérimenter sur FailyV, c'est plus chiant qu'autre chose quand on joue et aucune logique RP de devoir retirer complètement le masque ou le casque pour boire et manger. Et puis c'est un peu ridicule de voir les joueurs se cacher dans un buisson, voiture ou une pièce remplie de camera pour le faire. Imagine les agents du SWAT devoir retirer leurs casques/masques pour boire et manger ? Dans les films/series etc ils soulèvent que la partie basse du masque pour boire, on peut imaginer que le personnage fait juste ça pour boire et manger avec le masque dans GTA

**Comment by NariieL** [comment]
Hello! No thanks, the character is considered to be raising his mask slightly without revealing his identity. This change is not appreciated by the team. Thanks anyway. <3
