### ISSUE TITLE
[Vehicle] Briser le pare brise lorsque qu'un est éjecter du véhicules

### ISSUE THREAD

**Issue by TheAzylium** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#286]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

Véhicule

### Explain the current situation that you do not think is right.

Actuellement il ce peut que quelqu'un soit éjecter d'un véhicule sans que le pare brise ne soit cassé. Cela n'est pas cohérent #274

### How is the improvement you propose?

Lorsque quelqu'un est éjecter du véhicule automatiquement briser le pare brise

**Comment by NariieL** [comment]
Accepted, we'll look into it as soon as possible! <3

**Comment by Laikker** [comment]
Thanks for the proposition, the PR has been integrated in the main repo
