### ISSUE TITLE
[Phone] Option à activer pour contrôler l'interface du téléphone au clavier

### ISSUE THREAD

**Issue by MrKoddy** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

Phone

### Explain the current situation that you do not think is right.

Actuellement, le téléphone se dirige qu'à la souris, cela peut générer des problèmes de focus et d'input entre les commandes du jeu et du téléphone (missclick etc), ce n'est pas spécialement ergonomique quand il faut naviguer vite aussi

### How is the improvement you propose?

Activer une option dans les paramètres du téléphone pour avoir le choix de diriger l'interface du téléphone à la souris ou au clavier via les touches directionnelles, la touche Entrée et la touche Backspace afin de faciliter les contrôles. Réutiliser partie du code qui sert au Tetris ? Ca utilise les flèches directionnelles et des touches du clavier.

**Comment by NariieL** [comment]
No thanks! We don't like this option and prefer the phone to be mouse-only on SOZ. <3
