### ISSUE TITLE
[FDF] Ajout d'une livrée pour le Benson FDF

### ISSUE THREAD

**Issue by Jagaimo380** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

Vehicule

### Explain the current situation that you do not think is right.

Le Benson n'a pas de livrée spécifique pour FDF.

### How is the improvement you propose?

Modifier les livrés du Benson pour ajouter une livrée spécifique à FDF (ou remplacer une existante).
Ci-joint une image de la livrée FDF ainsi qu'un screen de celle-ci en jeu sur le Benson
![benson_extra_1](https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/assets/15649249/9099503b-45cf-47ae-839a-4cbdc16e6b24)
![20231123175113_1](https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/assets/15649249/cfe12adf-26db-40da-9b11-13598942ab79)

**Comment by NariieL** [comment]
Thanks, we'll look into it as soon as possible. <3
