### ISSUE TITLE
[dispensers] addition news items

### ISSUE THREAD

**Issue by nibor51** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#294]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

Dispenser

### Explain the current situation that you do not think is right.

Currently we only find coffee in hot drink dispensers, except players regularly ask for the addition of hot chocolate which provides the same effects as coffee.
And in the snack dispensers you only find sandwiches and even constant for the drink dispensers which only offer water.

### How is the improvement you propose?

I therefore suggest adding tea and hot chocolate to the hot drinks dispensed initially. (they will almost be a simple coffee clone)

Afterwards depending on the items of the style already present on the board, adding snack and soda items (chocolate bars, etc.) to the other types of dispensers, taking care that these items do not replace items coming from player farm circuit.
With nutritional stats making their excessive consumption harmful.

**Comment by NariieL** [comment]
<3
