### ISSUE TITLE
[SOZ-Phone] Taxe application

### ISSUE THREAD

**Issue by lucaslg** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Ajout d'une application téléphone permettant de consulter les taux des différentes taxes.

### Explain all the steps and mechanics clearly and precisely.

Application simple avec une unique page listant toutes les taxes.

### Why would this feature be useful?

Les taux des taxes ne sont pas affichés au joueur actuellement.
Les consulter permettra aux joueurs de râler au près de l'entité compétente pour les augmenter/baisser.

**Comment by NariieL** [comment]
Accepté !

**Comment by Laikker** [comment]
Integrated
