### ISSUE TITLE
[Masks] Adding missing masks

### ISSUE THREAD

**Issue by TheAzylium** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#324]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

Masks

### Explain the current situation that you do not think is right.

Currently, not all masks are available in the in-game mask store, including those from the latest versions.

### How is the improvement you propose?

I propose adding the missing masks in a special category named "⭐ Nouveauté" and including all the missing masks.

**Comment by Laikker** [comment]
Hello merci pour la proposition mais on avait déjà un rework des catégories des masques en cours avec l'ajout des manquants
