### ISSUE TITLE
[Improvement] Ajout des tenues reponsable d'atelier pour le NG

### ISSUE THREAD

**Issue by Thomysr** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#33]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

NG Cloakroom

### Explain the current situation that you do not think is right.

Il manque la tenue pour les reponsables d'atelier

### How is the improvement you propose?

Ajout des tenues pour homme et femmes responsable d'atelier.
Le fichier modifié est disponnible sur mon repo local dans la branche Tenue-NG-Responsable-Atelier

**Comment by joelwurtz** [comment]
On veut bien un screenshot aussi pour voir ce que ca donne :)

**Comment by Thomysr** [comment]
Hello, voici les screens des 2 tenues.

![ng-femme](https://user-images.githubusercontent.com/71434237/209967762-1ef829e2-fcf0-4d5b-ac09-d34cf3ae6b22.png)
![NG-homme](https://user-images.githubusercontent.com/71434237/209967767-a5ccb4cd-b413-4f87-b036-3e89045bf18c.png)

**Comment by NariieL** [comment]
Merci. <3
