### ISSUE TITLE
Lightning for DMC Mine

### ISSUE THREAD

**Issue by MrKoddy** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#336]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### In which category does your improvement fall?

Mapping

### Explain the current situation that you do not think is right.

DMC Mine has no lightning and it is difficult to see in the mine

### How is the improvement you propose?

I suggest to add lightning in the DMC Mine so players can see inside

https://streamable.com/oqvvbm

**Comment by Laikker** [comment]
Integrated
