### ISSUE TITLE
[Mapping/XMas] Adding XMas Props for housing and hammer tool

### ISSUE THREAD

**Issue by MrKoddy** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Adding custom XMas props for housing and hammer tool so players use them

### Explain all the steps and mechanics clearly and precisely.

Props already ready:
Igloo
XMas Ball
Happy Holidays Sign neon
Modular wires for attaching objects in the street or inside buildings so it doesnt fly in the air
XMas Wreath
Snowflake
XMas Star
XMas Stocking
XMas Santa Sleigh

And more props ideas in the near future:
Penguin with snowboard
XMas Wreath variants
Snow globe

### Why would this feature be useful?

For housing and hammer tool

**Comment by poulpito** [comment]
Hello @MrKoddy  est-ce que tu pourrai nous faire une PR avec les items qu'on regarde ?

**Comment by MrKoddy** [comment]
C'est fait https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/pull/349

**Comment by Laikker** [comment]
Integrated
