### ISSUE TITLE
[SOZCore Migration] Portage soz-driving-school vers soz-core

### ISSUE THREAD

**Issue by lanahrone** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#36]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

Permis

### Explain the current situation that you do not think is right.

La ressource `soz-driving-school` est actuellement écrite en `lua`.

### How is the improvement you propose?

Je propose le portage de la feature vers `soz-core` (`typescript`)
(Voir #35)

**Comment by NariieL** [comment]
Merci beaucoup @lanahrone pour cette migration ! <3 Contente de voir que tu continues d'aider SOZ à ton échelle même après tout ces longs mois. Tu as été notifié dans la note de patch !
