### ISSUE TITLE
[Brûleuse BB] : Aucune arme n'est recyclable

### ISSUE THREAD

**Issue by Zocaxu** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#38]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

BlueBird - Recycling - Weapons

### Explain the current situation that you do not think is right.

Aucune arme n'est recyclable dans la brûleuse de chez BlueBird. Ceci comprend les extincteurs et les autres armes des fdo. C'est problématique pour les extincteurs vides ou les armes cassées !

### How is the improvement you propose?

Je peux proposer au choix :

- D'autoriser le recyclage de TOUTES les armes, y compris les extincteurs.
- D'autoriser seulement les armes "périmées" (extincteur à 0%, arme à 0%).
- D'autoriser seulement les extincteurs (pleins et/ou vides).
- D'implementer une feature qui permet de "recharger" les extincteurs.

**Comment by NariieL** [comment]
Bonsoir,

Le fait que la bruleuse ne serve pas pour les armes est volontaire.

Tes propositions ne peuvent donc pas être acceptée.

Cependant, nous avions pour idée d'attribuer la sidérurgie à BlueBird. 

Si tu es prêt à te lancer sur un projet plus long que juste "Mettre l'autorisation des armes sur une Bruleuse", on pourra peut être voir ce qui est possible.

**Comment by Zocaxu** [comment]
Bonsoir !

Ok pour les armes. Cette issue était aussi destinée à résoudre le problème des extincteurs vides : impossible de les faire disparaître actuellement, ils sont donc stockés vides bêtement au LSMC.

Je ne sais pas ce que tu entends pas "La sidérurgie à BlueBird", ni le travail que cela représente, mais je serai ravi d'aider :)

**Comment by Zocaxu** [comment]
Dans l'immédiat je continue de travailler sur le soz-core et d'apprendre son fonctionnement. Je vais surement essayer de migrer des features déjà existantes pour tester le core avant de dev des nouvelles features. Je reviens surement vers toi une fois que je suis au point !
