### ISSUE TITLE
[Tenue LSMC] : Suggestions modification tenue hiver

### ISSUE THREAD

**Issue by Jules68Sanchez** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#39]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

LSMC - Clothing 

### Explain the current situation that you do not think is right.

Multiples bug de textures et chemises "non adaptées"  à la profession.

### How is the improvement you propose?

Proposition Femme : https://imgur.com/a/8oL0LvQ

Proposition Homme : https://imgur.com/a/U97ZBbH

- Modification de la chemise.

- Correction des bugs d'affichage au niveau des bras et du col.

**Comment by NariieL** [comment]
Hello !

Les tenues vont être de nouveau modifiées. Si tu y vois quelque chose à redire une fois la modification faite, n'hésites pas. 🙏🏼 

Merci beaucoup d'avoir voulu proposer ton aide à la correction de certains soucis. 💘
