### ISSUE TITLE
[DeMetal x Btarget] Two boxes of highlighted materials when arriving at the harvesting point.

### ISSUE THREAD

**Issue by NariieL** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#41]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of Issue

Two boxes of highlighted materials when arriving at the harvesting point. You can only interact with one of them.
![image](https://user-images.githubusercontent.com/104008465/210569557-28a41446-a85e-4afb-b54b-2a8d5c84e59c.png)

### Expected Behavior

There should only be one box.

### Reproduction Steps

By doing the normal commissioning procedure and arriving on site.

### Does it happen all the time ?

Occasionally

**Comment by Zocaxu** [comment]
PR #43 Devrait résoudre le bug !

**Comment by NariieL** [comment]
Merci pour la contribution, celle-ci sera notée sur lea prochaine note de patch. <3
