### ISSUE TITLE
[Tattoo x LSMC] When a doctor changes a player's outfit, his tattoos duplicate.

### ISSUE THREAD

**Issue by NariieL** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#42]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of Issue

Duplication of tattoos when the player is dressed in hospital clothes.
![image](https://user-images.githubusercontent.com/104008465/210571133-a2d87eba-5f21-40e7-bcfa-28e6839f9814.png)

### Expected Behavior

Tattoos should not duplicate themselves.

### Reproduction Steps

When a doctor puts us in a hospital outfit, the leg tattoos are duplicated on both legs

### Does it happen all the time ?

Yes

**Comment by Zocaxu** [comment]
![image](https://user-images.githubusercontent.com/72206163/210645484-de750c7f-ff88-4a1f-bb33-ba3e41359de5.png)

Le component 4 (jambes : Drawable 29 pour les hommes,) de la tenue Patient homme fait que la jambe gauche est rendue en miroir par rapport à la jambe droite, comme vu sur cette photo. C'est probablement une simplicité d'affichage.

Pour résoudre le problème, il faut changer ce Composent de la tenue patient homme. Je peux proposer le Drawable 61 pour les hommes ci-dessous. Le Drawable 21 convient pour les femmes et ne crée pas ce bug !

![image](https://user-images.githubusercontent.com/72206163/210645375-14ea4a6e-715a-442a-a91d-1d555c1982ee.png)
![image](https://user-images.githubusercontent.com/72206163/210646315-2a51b1b4-19ce-4fdb-a172-5023824a901e.png)

**Comment by Zocaxu** [comment]
#44 devrait résoudre le bug. On peut essayer de choisir un autre caleçon si celui là est moche !

**Comment by NariieL** [comment]
Merci pour la contribution, celle-ci sera notée sur la prochaine note de patch. <3
