### ISSUE TITLE
[Animation] Police Animation>Torch not visible to others

### ISSUE THREAD

**Issue by NariieL** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#45]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of Issue

Anim Torch visible only to the player who makes it

### Expected Behavior

The other player should also see animation.

### Reproduction Steps

Use the Flashlight animation in the F1 animation menu.

### Does it happen all the time ?

Yes

**Comment by Zocaxu** [comment]
Reproduit. Personne d'autre que le joueur ne voit l'animation.
Ce bug n'arrive pas pour les autres "scénarios" utilisés sur SOZ, comme le marteau-piqueur ou le marteau, alors qu'ils sont gérés exactement de la même façon dans le code. Pour moi, j'en déduis que le scénario est juste bugé et qu'il faudrait en choisir un autre ou faire différemment.

**Comment by Zocaxu** [comment]
![image](https://user-images.githubusercontent.com/72206163/211170891-538c49f1-a8b3-494a-838d-ac0cb65c3701.png)
![image](https://user-images.githubusercontent.com/72206163/211170898-039e3540-b639-4648-b8e3-106ab5cf2e09.png)

Bonjour !

Je peux proposer l'animation suivante avec la lampe torche. Le personnage peut se déplacer avec la torche en main. Les autres joueurs voient bien l'animation, même si l'éclairage est assez faible. Après les FDO on des lampes torches en tant qu'arme qui marchent bien il me semble.

Si c'est ok je PR :)

**Comment by NariieL** [comment]
Hello, accepté !

**Comment by NariieL** [comment]
Merci beaucoup pour cette correction ! <3 Tu as été notifié dans la note de patch.
