### ISSUE TITLE
[Improvement] Empêcher le Ragdoll après l'escorte.

### ISSUE THREAD

**Issue by Zocaxu** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#48]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of Issue

Quand un joueur est escorté alors qu'il est en ragdoll, il se relève (comportement normal). Mais lorsqu'il est lâché, il re-ragdoll.

### Expected Behavior

Il faudrait que le joueur reste debout après avoir été lâché, afin de potentiellement exécuter l'action qu'on lui demande (monter dans un véhicule, s'allonger, rentrer dans une cellule de détention, etc...).

### Reproduction Steps

Ragdoll puis se faire escorter et lâcher.

### Does it happen all the time ?

Oui.

**Comment by NariieL** [comment]
Hello,

**Attention, ce que tu proposes est un Improvement, pas un Bug Fix.**

De plus, nous ne désirons pas modifier cette mécanique : Lorsque tu tiens quelqu'un debout par la force alors qu'il se laisse tomber, il est normal que la personne retombe une fois lâchée. C'est au Joueur de contrôler la façon dont il désire agir, pas à son environnement sauf sous contrainte de force comme l'escorte.

La possibilité que le Joueur ne soit pas coopératif ajoute du piment au RP, cela donne des possibilités !

Merci tout de même pour la proposition, je ferme cette issue. <3
