### ISSUE TITLE
[Tenue Stonk x Civil] Remettre la tenue civile ne remet pas les bons bras.

### ISSUE THREAD

**Issue by NariieL** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#5]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of Issue

J'ai perdu mes bras en remettant mes vêtements civils après mon service à Stonk.
![image](https://user-images.githubusercontent.com/104008465/208317686-9ef02ee9-f2d9-49a1-88c8-01e5e8247c28.png)

### Expected Behavior

Mes bras devraient normalement apparaître, hors là, ils ont disparus.

### Reproduction Steps

Je remet ma tenue civil dans le vestiaire de STONK.

### Does it happen all the time ?

Oui

**Comment by AlexPresso** [comment]
Hello,
J'essaie de reproduire le souci mais avec la tenue civile de mon personnage, le problème ne semble pas se présenter.
Serait-il possible d'avoir la `cloth_config` de l'impression d'écran, à injecter en db pour tester ? merci bien :)

**Comment by Zocaxu** [comment]
Je suis en train de faire correspondre manuellement tous les tops aux bons torses. Ca prend un peu de temps, mais une fois cela fait, on aura plus du tout de problème de bras/corps invisibles. On pourra même ajouter facilement les gants et d'autres modèles de vêtements si vous le souhaitez :)

**Comment by NariieL** [comment]
> Hello, J'essaie de reproduire le souci mais avec la tenue civile de mon personnage, le problème ne semble pas se présenter. Serait-il possible d'avoir la `cloth_config` de l'impression d'écran, à injecter en db pour tester ? merci bien :)

J'ai relancé Brouznouf, il voit ça asap !

**Comment by NariieL** [comment]
> Je suis en train de faire correspondre manuellement tous les tops aux bons torses. Ca prend un peu de temps, mais une fois cela fait, on aura plus du tout de problème de bras/corps invisibles. On pourra même ajouter facilement les gants et d'autres modèles de vêtements si vous le souhaitez :)

J'avoue que si tu veux t'occuper des gants, tu nous retires une épine énorme du pied.

**Comment by Zocaxu** [comment]
> > Hello, J'essaie de reproduire le souci mais avec la tenue civile de mon personnage, le problème ne semble pas se présenter. Serait-il possible d'avoir la `cloth_config` de l'impression d'écran, à injecter en db pour tester ? merci bien :)
> 
> 
> 
> J'ai relancé Brouznouf, il voit ça asap !

Les fringues sont un enfer. J'ai le sentiment que si y'a pas quelqu'un qui se coltine de hardcode toutes les configs qui marchent ensemble sans trop buguer, on arrivera jamais à avoir un truc propre. Je commence par les torses, on améliorera après.

**Comment by Laikker** [comment]
> > > Hello, J'essaie de reproduire le souci mais avec la tenue civile de mon personnage, le problème ne semble pas se présenter. Serait-il possible d'avoir la `cloth_config` de l'impression d'écran, à injecter en db pour tester ? merci bien :)
> > 
> > 
> > J'ai relancé Brouznouf, il voit ça asap !
> 
> Les fringues sont un enfer. J'ai le sentiment que si y'a pas quelqu'un qui se coltine de hardcode toutes les configs qui marchent ensemble sans trop buguer, on arrivera jamais à avoir un truc propre. Je commence par les torses, on améliorera après.

Pourquoi tu penses qu'il faille hard codé les torses, la fonction GetProperTorso fourni déjà çà.
Je penses que c'est un problème de shop, avec ce scénario:
-Avoir un tenue civile sans manche
-Mettre une tenue de travail avec des manches
-Acheter des chaussures dans un magasin
-Enlever la tenue de travail
=> Les bras ont disparu car l'achat a appliqué les bras courant (donc de la tenue de travail) à la tenue civile
voi soz-shops/client/shops/clothing.lua ligne 138

**Comment by Zocaxu** [comment]
Tu as tout à fait raison pour le bug lié à la tenue de travail !

En revanche la fonction "GetProperTorso" ne revoit pas toujours le bon torse, à en jugé par le nombre de bug visuels restants sur les tenues femme (et homme pour les vestes ouvertes notamment).

Quoi qu'il en soit nous venons de finir de hard coder les bons torses pour TOUS les hauts hommes et femmes (oui... les 700...). Ca devrait éradiquer complètement ce bug, en plus de permettre d'ajouter (beaucoup) plus de vêtements.

Les prochaines étapes sont : les gants et les sous-vêtements pour les tenues ouvertes.

Une PR arrive bientôt pour cette issue #5

**Comment by NariieL** [comment]
This is no longer an issue.
