### ISSUE TITLE
[BTarget FDO] Couleur des icônes BTarget FDO

### ISSUE THREAD

**Issue by Zocaxu** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#50]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of Issue

Les icônes des interactions BTarget (Escorter, fouiller, menotter, démenotter) n'ont pas la bonne couleur : ils apparaissent bleues (couleur LSPD) pour tout le monde.

### Expected Behavior

Leur couleur devrait s'adapter au métier du personnage (Vert clair pour le LSMC, bleu LSPD, vert foncé Kaki BCSO, vert foncé STONK).

### Reproduction Steps

Etre de l'un des métiers FDO et BTarget un joueur en étant en service.

### Does it happen all the time ?

Oui.

**Comment by NariieL** [comment]
Hello,

**Attention, ce que tu proposes est un Improvement, pas un Bug Fix.**

Aucun souci pour cet ajout. Si le coeur t'en dit, tu peux faire un recheck de toutes les couleurs de toutes les entreprises/actions.

**Comment by Zocaxu** [comment]
Ca marche ! Je ferai attention à spécifier les improvements.
Je n'ai pas vu d'autres soucis de couleur :)

**Comment by NariieL** [comment]
Merci beaucoup pour ta PR ! <3 Tu as été notifié dans la note de patch !
