### ISSUE TITLE
[Tenues LSMC] : propositions de modifications

### ISSUE THREAD

**Issue by LarryCooperSOZ** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#53]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

LSMC | Tenue d'hiver + hazmat

### Explain the current situation that you do not think is right.

**Tenue hiver** : choix d'une couleur plus adaptée à la médecine tout en conservant les couleurs du LSMC via le logo sur chaque manche. La première tenue d'hiver avait beaucoup plus à l'ensemble des joueurs :)

**Tenue Hazmat** : tenue blanche, typique des tenues lors d'épidémies

### How is the improvement you propose?

**Tenue hiver :** 

- [Tenue hiver Femme](https://cdn.discordapp.com/attachments/976012189137784842/1061372360143421500/image.png)
- [Tenue hiver Homme](https://cdn.discordapp.com/attachments/976012189137784842/1061370135522332712/image.png)

Retour au bleu de la veste de base avec le logo LSMC sur les épaules.
Modification de la chemise (unisex) qui s'adapte mieux avec la veste et qui est raccord avec la couleur des gants.

**Tenue hazmat :** 

- [Tenue hazmat Femme](https://cdn.discordapp.com/attachments/976012189137784842/1061373475723411536/image.png)
- [Tenue hazmat Homme](https://cdn.discordapp.com/attachments/976012189137784842/1061373875167965314/image.png)

Si l'improvement est ok, on peut fournir tous les éléments pour merge ensuite sur le server SoZ.

**Comment by NariieL** [comment]
Hello ! Accepté !

**Comment by Zocaxu** [comment]
@LarryCooperSOZ J'ai fait une PR conforme à tes changements comme tu me l'as demandé <3

**Comment by LarryCooperSOZ** [comment]
Nikel merci ! Pour info NariieL on a bossé ensemble avec Zocaxu sur le projet d'où la PR. Merci à vous deux !

**Comment by LarryCooperSOZ** [comment]
> Hello ! Accepté !

**Comment by LarryCooperSOZ** [comment]
Hello ! 

J'ai vu que la PR avait été merge, merci beaucoup simplement on a encore la couleur verte de l'ancienne veste. 🙂

[Veste actuelle](https://cdn.discordapp.com/attachments/976012189137784842/1064832543993634886/image.png)
[Veste souhaitée](https://cdn.discordapp.com/attachments/976012189137784842/1061370135522332712/image.png)

@Zocaxu a remplacé la PR avec la nouvelle couleur. Y'a plus qu'à merge :)

**Comment by NariieL** [comment]
Il faut une nouvelle PR pour ço !
