### ISSUE TITLE
[Vêtements] Ajout des gants

### ISSUE THREAD

**Issue by Zocaxu** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#59]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Je propose d'ajouter les gants aux vêtements achetables et à équiper pour les joueurs. 
Vidéo de démonstration : 

https://user-images.githubusercontent.com/72206163/212565948-fa83e863-5824-46f3-b924-68aa7c77ba77.mp4

### Explain all the steps and mechanics clearly and precisely.

Je propose les éléments détaillés suivants :

- Ajout dans la base de données des éléments permettant d'intégrer les gants dans les vêtements des joueurs. Je peux fournir cette base de donnée sous format Excel, Google Doc, CSV. Celle-ci est complètement compatible avec les autres vêtements déjà présents sur SOZ.
- Les gants sont achetables dans les Binco et Suburban.
- Les gants sont sauvegardés dans la penderie du joueur en même temps que le reste de ses vêtements.
- Ajout de la possibilité d'afficher/cacher les gants du joueurs via une cache à cocher identique aux autres vêtements.

- Cet ajout utilise les nouveaux torses implémentés dans la PR #47. J'en ai besoin !
- Cet ajout est fait en Lua et n'est pas intégré au soz-core. Cela demanderait de transférer beaucoup de choses vers le core, et pour l'instant je ne l'ai pas envisagé.

Eléments non développés :

- Il est impossible d'afficher les gants si le haut n'est pas affiché. (impossible d'être torse nu avec les gants)
- Lorsque un joueur achète un nouveau haut, ses gants actuels sont supprimés, car ces derniers ne sont a priori pas compatibles avec son haut actuel.
- Certains modèles de gants sont compatibles avec tous les hauts, mais certains ne sont compatibles qu'avec certains hauts. Ces deux catégories sont intégrées à la base de donnée, et c'est à cause de ces deux catégories que les 2 éléments non développés ci-dessus existent. Garder uniquement les gants omni-compatibles permettrait de se débarrasser des deux points précédents.

Eléments à discuter :

- Manière dont les gants sont restock dans les magasins concernés. Plusieurs idées : disponibles à l'infini / Restock avec les sous-vêtements / Restock avec un nouvel item propre à FFS.

Je précise que l'ensemble du code et de la base de données sont le résultat de mon travail et de l'aide d'autres joueurs de SOZ dans le cadre de l'Open-Source.

### Why would this feature be useful?

Cet ajout permet plus de personnalisation des joueurs, et plus d'immersion, surtout en hiver !

**Comment by Zocaxu** [comment]
Question supplémentaire qui est liée :
Lors de l'achat d'un vêtement, seulement ce vêtement précis (même modèle et même couleur) voit son stock diminué alors que lors du restock par FFS, 1 seule ressource de FFS permet de restock toutes les couleurs de ce modèle de vêtement. Est-ce volontaire ?

**Comment by Zocaxu** [comment]
EDIT : 
- Je propose d'ajouter certains gants (en laine, gants de ski etc...) aux bincos/suburbans et les gants un peu plus chics (en cuir, de soirée, etc...) aux Ponsonbys.
- Nouveaux crafts de gants pour FFS. Recettes proposées
   - Normal => 1 cuir + 20 fibres naturelles (pour comparer, 1 cuir 2 latex pour les chaussures) => reward de $30 (pour comparer, 40 pour des chaussures, 20 pour des sous-vêtements)
   - Luxe => 2 cuirs + 40 fibres naturelles (pour comparer, 2 cuir 4 latex pour les chaussures) => reward de $60 (pour comparer, 80 pour des chaussures luxe, 40 pour des sous-vêtements luxe)

- Il peut être possible de porter **certains** (la plupart en réalité) gants sans haut, si vous le souhaitez. Personnellement, ça me semble assez inutile.
- Par contre quand un joueur achète un nouveau haut, il devra racheter des gants après. Si c'est vraiment trop embêtant je peux essayer d'implémenter une correspondance. _Mais bon ça fait du travail en plus pour les joueurs, pourquoi pas..._

Evidemment ce n'est qu'une proposition, j'attends le retour, tout est modifiable.

**Comment by Zocaxu** [comment]
Propositions pour les icones les nouveaux crafts FFS :

Normal :
<img src="https://user-images.githubusercontent.com/72206163/213540075-16f13c9d-a963-47b7-89db-7497285ad59d.png" width="200" height="200"> <img src="https://user-images.githubusercontent.com/72206163/213540123-7a36605e-4ab0-42fc-9a3a-561c119103ef.png" width="200" height="200"> <img src="https://user-images.githubusercontent.com/72206163/213540188-d29bb625-3017-4367-9fca-869f8c31523b.png" width="200" height="200">


Luxe :
<img src="https://user-images.githubusercontent.com/72206163/213541446-8dfce9d1-ca9a-4e9d-b955-20711b2243db.png" width="200" height="200"><img src="https://user-images.githubusercontent.com/72206163/213540283-10fe70de-4b6d-441a-aceb-3a08fb257f5f.png" width="200" height="200"><img src="https://user-images.githubusercontent.com/72206163/213540313-00709b3d-b4b8-41a9-b401-0deb889e3a7d.png" width="200" height="200">

**Comment by Zocaxu** [comment]
Bonjour !
La feature et la PR associée ainsi que la BDD sont prêtes !
Je n'attends plus que toi @NariieL pour valider/modifier/choisir ce que j'ai proposé concernant les choix d'implémentation, les crafts, rewards pour FFS et les icones.

**Comment by DreamXZE-GH** [comment]
> Question supplémentaire qui est liée :
Lors de l'achat d'un vêtement, seulement ce vêtement précis (même modèle et même couleur) voit son stock diminué alors que lors du restock par FFS, 1 seule ressource de FFS permet de restock toutes les couleurs de ce modèle de vêtement. Est-ce volontaire ?

Je me permet de te répondre, oui c'est voulu. Chaque magasin a son stock, et le restock se fait de manière random sur certain modèle de certain magasin (peut import ou le restock est fait).
Actuellement la pile de vetement est divisé par batch de 10, et cela rempli par 10 des modèles random dans des boutiques random.

Si tu as 55 haut sur toi et que tu restock, tu vas donc rajouter 10 stock à 5 modèle random dans des boutique random, puis 5 dans un sixième modèle. C'est la même pour les pantalon/chaussure et version de luxe

Les versions normal restock Binco et Suburban, les version de luxe remplisse les Sponsiboy
