### ISSUE TITLE
Code Improvement(natives): replace native GetPlayerPed(-1)

### ISSUE THREAD

**Issue by spacevx** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#61]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

This "improvement" is only a improvement in the code, it's not a feature for the server

But ressources impacted by this modification are
 <ul>
   <li><a href="https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/tree/oss/resources/%5Bsoz%5D/soz-core">soz-core</a></li>
   <li><a href="https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/tree/oss/resources/%5Bsoz%5D/soz-ems">soz-ems</a></li>
   <li><a href="https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/tree/oss/resources/%5Bsoz%5D/soz-hud">soz-hud</a></li>
   <li><a href="https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/tree/oss/resources/%5Bsoz%5D/soz-items">soz-items</a></li>
   <li><a href="https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/tree/oss/resources/%5Bsoz%5D/soz-jobs">soz-jobs</a></li>
   <li><a href="https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/tree/oss/resources/%5Bsoz%5D/soz-map">soz-maps</a></li>
   <li><a href="https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/tree/oss/resources/%5Bsoz%5D/soz-utils">soz-utils</a></li>
</ul>

Every ressource who was using the native <a href="https://docs.fivem.net/natives/?_0x43A66C31C68491C0">GetPlayerPed(-1)</a> was impacted (client-side only)

### Explain the current situation that you do not think is right.

PlayerPedId() is more faster than GetPlayerPed(-1), this modification will not impact the gameplay for the players since the 2 natives are basically the same

Everything is explained on the <a href="https://forum.cfx.re/t/question-difference-between-getplayerped-1-and-playerpedid/539437">cfx.re forum</a>

### How is the improvement you propose?

Just replace this native #60

**Comment by NariieL** [comment]
Merci beaucoup pour ta PR @ahcenezdh ! <3 Tu as été mentionné dans la note de patch. Les petites contributions comme les tiennes sont les meilleures.
