### ISSUE TITLE
Ajouter des tenues pour les associations

### ISSUE THREAD

**Issue by Thomysr** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#68]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Ajouter des tenues pour les différentes associations. Pour le moment, il n'est pas possible de modifier les vêtements par d'autres (impossible de stream des tenues custo).

### Explain all the steps and mechanics clearly and precisely.

Pouvoir ajouter des tenues d'associations dans les boutiques.

### Why would this feature be useful?

La possibilité de porter des vêtements custo rajoute de la cohérence dans le RP, les associations n'ont pas de signe distinctif pour le moment. La possibilité de pouvoir les acheter même si on n'est pas membre de l'association permet également de créer du RP.

**Comment by NariieL** [comment]
Ola! No thanks, we prefer that they buy - register an outfit directly in the existing shops. Thanks anyway. <3
