### ISSUE TITLE
Correction texte revente essence et Kérozène pour MTP

### ISSUE THREAD

**Issue by Ouragann** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#69]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

Michel Transport Petrol revente

### Explain the current situation that you do not think is right.

Actuellement le texte qui indique la revente est la suivante : 
"Vous avez revendu 10L d'essence"
"Vous avez revendu 10L de Kérozène"

### How is the improvement you propose?

Changer la ligne dans le fichier 

https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/blob/37d2bd82ce6fd57a692bb1699c382f10ed0d8e46/resources/%5Bsoz%5D/soz-jobs/server/jobs/oil.lua#L221

`TriggerClientEvent("hud:client:DrawNotification", Player.PlayerData.source, "Vous avez ~g~revendu~s~ 100L d'essence")`

Et j'ajoute qu'il faut modifier aussi celle pour le kérozène : 

https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/blob/37d2bd82ce6fd57a692bb1699c382f10ed0d8e46/resources/%5Bsoz%5D/soz-jobs/server/jobs/oil.lua#L233

`TriggerClientEvent("hud:client:DrawNotification", Player.PlayerData.source, "Vous avez ~g~revendu~s~ 100L de kérosène")`

**Comment by Zocaxu** [comment]
Si tu as déjà une branche avec les modifications, n'hésite pas à faire une Pull Request en mentionnant cette issue !

**Comment by Ouragann** [comment]
> Si tu as déjà une branche avec les modifications, n'hésite pas à faire une Pull Request en mentionnant cette issue !

Alors je suis désolé je débute sur Guthub et je n'ai pas compris, sur le discord on m'avais dis de faire une issue ^^"
Je pense à déja savoir quoi modifier, il faut que je propose un pull request au lieu de faire une issue c'est ça ?

**Comment by Zocaxu** [comment]
Pour chaque modification que tu proposes, il faut une issue, donc tu as bien fait d'en faire une !

La prochaine étape est de proposer t'intégrer tes changements directement dans le code de SOZ, pas seulement de décrire ce qu'il faut changer, mais de le changer effectivement ! C'est en faisant une Pull request que tu fais cela.

**Comment by Ouragann** [comment]
Ah, le problème c'est que je ne sais pas comment faire, je ne sais meme pas faire la première étape qui me demande de choisir entre les deux versions...
