### ISSUE TITLE
Add Edit Button on conversations with existing contact

### ISSUE THREAD

**Issue by Maskowh** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#75]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

Téléphone

### Explain the current situation that you do not think is right.

Dans une conversation avec un numéro non enregistré, un bouton pour l'ajouter aux contacts est présent.

Dans une conversation avec un numéro enregistré, si l'on veut éditer le contact (par exemple en apprenant un changement d'entreprise, affiliation, grade dans un message) on doit actuellement: quitter l'application Messages, ouvrir l'application Contact, recherche le contact et finalement l'éditer.

### How is the improvement you propose?

La présente Issue propose de rajouter un bouton "éditer le contact" pour les conversations avec numéro enregistré, au même emplacement que le "Ajouter contact" pour les numéros non enregistrés.

Aperçu de la feature: https://youtu.be/3jsY_1TvokQ

**Comment by NariieL** [comment]
It's been a while since this was listed on the patch note, thanks again. <3
