### ISSUE TITLE
[Clefs] Différencier les clefs de voiture et de logement

### ISSUE THREAD

**Issue by Zocaxu** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#78]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

Clefs

### Explain the current situation that you do not think is right.

Les clefs de voiture et les clefs d'appartement ont le même icône, elles sont indifférenciables visuellement.

### How is the improvement you propose?

Je propose d'ajouter une icône pour les clefs de voiture et de garder l'icône actuelle pour les clefs d'appartement.
Voici quelques propositions (clairement, on peut en faire plein d'autres si jamais) :
<img src="https://user-images.githubusercontent.com/72206163/215465616-fc0fe50a-d2be-4a16-89da-b9a4c76120ee.png" width="200" height="200"> <img src="https://user-images.githubusercontent.com/72206163/215465703-3f2db737-2af4-4222-8610-9905371bd2c6.png" width="200" height="200"> <img src="https://user-images.githubusercontent.com/72206163/215465739-746cb1f4-b0ed-4f61-8d2d-a1fe619f7a17.png" width="200" height="200">

**Comment by NariieL** [comment]
Validé pour la troisième image ! Oublie pas de retirer le fond blanc.
![image](https://user-images.githubusercontent.com/104008465/215484189-c121f21d-10fa-474c-b5ca-168275d1877f.png)
