### ISSUE TITLE
Add label on vehicle keys icons

### ISSUE THREAD

**Issue by Maskowh** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#80]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

Keys/Inventory

### Explain the current situation that you do not think is right.

Quand on a plusieurs clés de véhicules (en tant que joueur NG, j'ai déjà eu 20+ clés sur moi), il est peu pratique de défiler sur toutes les clés pour savoir quelle est la plaque afin de donner la bonne clé à un autre joueur.

### How is the improvement you propose?

Ajoute à la manière des raccourcis d'inventaire la plaque d'immatriculation sur l'icône de la clé, comme une étiquette.

![image](https://user-images.githubusercontent.com/123783610/215855914-c0001146-60f6-45c8-b465-fabc1b1e0029.jpg)

**Comment by NariieL** [comment]
Hello ! Merci beaucoup pour la modification, c'est accepté sans problème, bonne initiative.
