### ISSUE TITLE
Notif "Votre appel vient d'être pris" indique quelle entreprise a pris l'appel

### ISSUE THREAD

**Issue by Maskowh** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#82]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

Notif HUD

### Explain the current situation that you do not think is right.

Actuellement, quand on a plusieurs appels entreprises envoyés, si l'un d'eux est pris, on ne sait pas lequel.

### How is the improvement you propose?

Ajouter l'information de quelle entreprise a pris l'appel

![image2](https://user-images.githubusercontent.com/123783610/215914164-ea37f936-47cb-4b6b-9467-5a63ddf8bf46.png)

**Comment by NariieL** [comment]
It's been a while since this was listed on the patch note, thanks again. <3
