### ISSUE TITLE
Menus: Faire défiler les titres au lieu de les tronquer

### ISSUE THREAD

**Issue by Maskowh** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#84]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

Menus

### Explain the current situation that you do not think is right.

Actuellement quand un "titre" de menu est trop long, il est tronqué.

![old](https://user-images.githubusercontent.com/123783610/216118642-abdc817b-f73e-45e2-8890-29ff7b36adf6.png)

### How is the improvement you propose?

Au lieu de les tronquer, les titres pourraient défiler si ils sont trop long, de manière à ce qu'ils puissent être lus en entier.

https://user-images.githubusercontent.com/123783610/216118907-99e48707-4439-4c74-9f66-ecd1bbbb0dff.mp4

**Comment by NariieL** [comment]
Coucou ! Merci beaucoup pour la proposition, c'est un grand oui. On s'en occupe dès qu'on trouve le temps ! <3

**Comment by Maskowh** [comment]
> Coucou ! Merci beaucoup pour la proposition, c'est un grand oui. On s'en occupe dès qu'on trouve le temps ! <3

Hello, j'ai déjà fait une PR, normalement c'est ok, mais il y a l'ajout d'une dépendence, dont vous ne voudrez pas forcément.

**Comment by NariieL** [comment]
Je laisse Brouznouf review pour ça, je ne fais que valider la proposition. ❤️

**Comment by Maskowh** [comment]
Hello @NariieL tant que j'y suis, j'en profite pour mettre cette anim de défilement sur tous les textes tronqués?
Actuellement, je l'ai fait que pour les titres de menus, mais il y a d'autres endroits où du texte est tronqué et où je peux le faire défiler:
- nom des contacts dans la liste des contacts
- nom des contacts dans les conversations
- nom des contacts dans le journal d'appel
- nom d'un contact lors d'un appel
- titre des applis sur la page d'accueil du téléphone
- choix dans les menus

Mis à part le dernier qui semble plus complexe, c'est le même principe.

Dans le cas où j'ai ton go pour le faire: Même Issue/PR où j'en fais une autre?

J'ai testé avec le nom des contacts dans la liste des contacts par exemple:
https://user-images.githubusercontent.com/123783610/216422125-39c566f6-2f8a-4883-8bcd-98ae50ed91c7.mp4

**Comment by Maskowh** [comment]
Du coup j'ai décidé de le faire sur une autre issue, #90 
Les choix des menus seront pour plus tard, quand j'aurais trouver un moyen de le faire proprement.
