### ISSUE TITLE
Phone: Faire défiler les textes au lieu de les tronquer

### ISSUE THREAD

**Issue by Maskowh** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#88]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

Phone

### Explain the current situation that you do not think is right.

Plusieurs textes sur le téléphones sont tronqués si ils sont trop longs.

Voici ceux que j'ai identifié:
- Nom des applis sur l'écran d'accueil
- Nom des conversations dans la liste des conversations dans l'appli Messages
- Nom de la conversation dans une conversation ouverte dans l'appli Messages
- Nom des contacts dans la liste des contacts
- Nom des contacts dans l'historique d'appel
- Nom du contact sur l'écran d'appel
- Nom du personnage dans l'appli Banque

### How is the improvement you propose?

Je propose de les faire défiler plutôt que de les tronquer, afin que toute le texte puisse être lu.

https://user-images.githubusercontent.com/123783610/216587567-e673eda2-71b0-44e4-a076-5c387bcc4fa9.mp4

**Comment by Zocaxu** [comment]
Actuellement quand tu ouvres le téléphone, le texte se met à défiler instantanément, du coup on a pas le temps de lire le début du premier mot.
Est-ce que tu penses que c'est faisable d'attendre 2-3 secondes avant que le mot se mette à défiler ? C'est comme ça que sont réalisés les textes défilants en général. (Sinon super propal ❤️)

**Comment by Maskowh** [comment]
Effectivement, j'aime mieux comme ça, merci pour la proposition. J'ai mis 2s de fixe puis 5s de défilement.


https://user-images.githubusercontent.com/123783610/216605255-38bcb1a7-7d4c-4550-9ad9-63d5d4296e19.mp4

**Comment by Zocaxu** [comment]
C'est top comme ça, 👏🏻
Même proposition pour les menus du coup 🙌🏻

**Comment by Maskowh** [comment]
Evolution proposée suite aux retours de @NariieL sur la PR: Ne faire défiler les textes que lorsque la souris est dessus

https://youtu.be/YRTRYhvFeXQ

**Comment by NariieL** [comment]
After several tests, we do not like this modification. Sorry and thanks to you. <3
