### ISSUE TITLE
[Prima] Issues with Prima

### ISSUE THREAD

**Issue by DarkEag** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#9]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of Issue

When I do "cd resources/[soz]/soz-core && yarn run prisma migrate deploy" I get these errors:

Invalid default value for 'end' in 'phone_calls'
Invalid default value for 'created_at' in 'add_player_creation_date'

After this everything else works (I put "DEFAULT CURRENT_TIMESTAMP(0)" directly on both to bypass the issue meanwhile)

### Expected Behavior

It shouldn't do errors

### Reproduction Steps

"cd resources/[soz]/soz-core && yarn run prisma migrate deploy"

### Does it happen all the time ?

Yes

**Comment by joelwurtz** [comment]
What is your mariadb version ? 

It should work fine on latest versions (at least it work on our current version : mariadb 10.7.1)

**Comment by DarkEag** [comment]
My version is 10.4.25-MariaDB. I'll try the newest one

**Comment by Povers** [comment]
Works well in version 10.6.10 too.

**Comment by DarkEag** [comment]
Update on the issue:
https://stackoverflow.com/questions/36374335/error-in-mysql-when-setting-default-value-for-date-or-datetime
It's because we need to activate the Strict mode for it to accept 0000

**Comment by DarkEag** [comment]
Update on the issue:
I had NO_ZERO_IN_DATE,NO_ZERO_DATE, in the sql mode in "Variables" so it worked when deleting it. It's the default configuration of Xampp. All good thanks :)
