### ISSUE TITLE
[Téléphone] Options historique d'appel

### ISSUE THREAD

**Issue by Maskowh** [SOZ-Faut-etre-Sub/SOZ-FiveM-Server#99]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### In which category does your improvement fall?

Téléphone

### Explain the current situation that you do not think is right.

Options disponibles pour un numéro non enregistré dans l'historique d'appel:
![image](https://user-images.githubusercontent.com/123783610/216810364-6ff30afe-24f3-462d-893a-d12df41b6ff1.png)
Actuellement: "Appeler" et "Ajouter le Contact".

Options disponibles pour un numéro enregistré dans l'historique d'appel:
![image](https://user-images.githubusercontent.com/123783610/216810404-cc06812c-6995-42a8-b3fc-48b19e3a6448.png)
Actuellement: "Appeler".

### How is the improvement you propose?

- Ajouter l'option "Editer" dans le cas d'un contact enregistré
- Ajouter l'option "Message" dans les deux cas
- Ajouter les options "Envoyer ma position" et "Envoyer ma destination"

**Comment by Moustash** [comment]
Il serait peut être intéréssant d'ajouter une option pour supprimer un appel de l'historique si on souhaite en faire le ménage partiel ?

**Comment by NariieL** [comment]
Nous sommes pour ! <3

**Comment by NariieL** [comment]
Sauf pour : Ajouter les options "Envoyer ma position" et "Envoyer ma destination"

Ajouter l'option "Editer" dans le cas d'un contact enregistré
Ajouter l'option "Message" dans les deux cas
Est ok !

**Comment by Maskowh** [comment]
PR créé.


https://github.com/SOZ-Faut-etre-Sub/SOZ-FiveM-Server/assets/123783610/75061c1a-0a8e-4840-837f-3a33687c287d
